// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

//go:build windows

package policydeviceguard

import (
	csp "github.com/deploymenttheory/go-bindings-wmi/runtime/csp"
	wmi "github.com/deploymenttheory/go-bindings-wmi/runtime/wmi"
)

// Service drives this CSP area's policies through the MDM bridge.
// Construct it with New, passing a wmi.Service connected to the bridge
// namespace (csp.Connect, which requires the SYSTEM account).
type Service struct{ svc *wmi.Service }

// New returns a Service bound to a connected bridge session.
func New(svc *wmi.Service) *Service { return &Service{svc: svc} }

// GetConfigureSystemGuardLaunch reads the effective value of ConfigureSystemGuardLaunch.
func (s *Service) GetConfigureSystemGuardLaunch() (int64, error) {
	v, err := csp.Read(s.svc, ConfigureSystemGuardLaunch)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetConfigureSystemGuardLaunch sets ConfigureSystemGuardLaunch (OMA-DM Add/Replace).
func (s *Service) SetConfigureSystemGuardLaunch(v int64) error {
	return csp.Set(s.svc, ConfigureSystemGuardLaunch, v)
}

// DeleteConfigureSystemGuardLaunch unmanages ConfigureSystemGuardLaunch (OMA-DM Delete).
func (s *Service) DeleteConfigureSystemGuardLaunch() error {
	return csp.Delete(s.svc, ConfigureSystemGuardLaunch)
}

// GetEnableVirtualizationBasedSecurity reads the effective value of EnableVirtualizationBasedSecurity.
func (s *Service) GetEnableVirtualizationBasedSecurity() (int64, error) {
	v, err := csp.Read(s.svc, EnableVirtualizationBasedSecurity)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetEnableVirtualizationBasedSecurity sets EnableVirtualizationBasedSecurity (OMA-DM Add/Replace).
func (s *Service) SetEnableVirtualizationBasedSecurity(v int64) error {
	return csp.Set(s.svc, EnableVirtualizationBasedSecurity, v)
}

// DeleteEnableVirtualizationBasedSecurity unmanages EnableVirtualizationBasedSecurity (OMA-DM Delete).
func (s *Service) DeleteEnableVirtualizationBasedSecurity() error {
	return csp.Delete(s.svc, EnableVirtualizationBasedSecurity)
}

// GetLsaCfgFlags reads the effective value of LsaCfgFlags.
func (s *Service) GetLsaCfgFlags() (int64, error) {
	v, err := csp.Read(s.svc, LsaCfgFlags)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetLsaCfgFlags sets LsaCfgFlags (OMA-DM Add/Replace).
func (s *Service) SetLsaCfgFlags(v int64) error { return csp.Set(s.svc, LsaCfgFlags, v) }

// DeleteLsaCfgFlags unmanages LsaCfgFlags (OMA-DM Delete).
func (s *Service) DeleteLsaCfgFlags() error { return csp.Delete(s.svc, LsaCfgFlags) }

// GetMachineIdentityIsolation reads the effective value of MachineIdentityIsolation.
func (s *Service) GetMachineIdentityIsolation() (int64, error) {
	v, err := csp.Read(s.svc, MachineIdentityIsolation)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetMachineIdentityIsolation sets MachineIdentityIsolation (OMA-DM Add/Replace).
func (s *Service) SetMachineIdentityIsolation(v int64) error {
	return csp.Set(s.svc, MachineIdentityIsolation, v)
}

// DeleteMachineIdentityIsolation unmanages MachineIdentityIsolation (OMA-DM Delete).
func (s *Service) DeleteMachineIdentityIsolation() error {
	return csp.Delete(s.svc, MachineIdentityIsolation)
}

// GetRequireMicrosoftSignedBootChain reads the effective value of RequireMicrosoftSignedBootChain.
func (s *Service) GetRequireMicrosoftSignedBootChain() (int64, error) {
	v, err := csp.Read(s.svc, RequireMicrosoftSignedBootChain)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetRequireMicrosoftSignedBootChain sets RequireMicrosoftSignedBootChain (OMA-DM Add/Replace).
func (s *Service) SetRequireMicrosoftSignedBootChain(v int64) error {
	return csp.Set(s.svc, RequireMicrosoftSignedBootChain, v)
}

// DeleteRequireMicrosoftSignedBootChain unmanages RequireMicrosoftSignedBootChain (OMA-DM Delete).
func (s *Service) DeleteRequireMicrosoftSignedBootChain() error {
	return csp.Delete(s.svc, RequireMicrosoftSignedBootChain)
}

// GetRequirePlatformSecurityFeatures reads the effective value of RequirePlatformSecurityFeatures.
func (s *Service) GetRequirePlatformSecurityFeatures() (int64, error) {
	v, err := csp.Read(s.svc, RequirePlatformSecurityFeatures)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetRequirePlatformSecurityFeatures sets RequirePlatformSecurityFeatures (OMA-DM Add/Replace).
func (s *Service) SetRequirePlatformSecurityFeatures(v int64) error {
	return csp.Set(s.svc, RequirePlatformSecurityFeatures, v)
}

// DeleteRequirePlatformSecurityFeatures unmanages RequirePlatformSecurityFeatures (OMA-DM Delete).
func (s *Service) DeleteRequirePlatformSecurityFeatures() error {
	return csp.Delete(s.svc, RequirePlatformSecurityFeatures)
}
