// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

package policywindowsdefendersecuritycenter

// DisableAccountProtectionUI allowed values.
const (
	DisableAccountProtectionUIDisableTheUsersCanSeeTheDisplayOfTheAccountProtectionAreaInWindowsDefenderSecurityCenter   int64 = 0
	DisableAccountProtectionUIEnableTheUsersCannotSeeTheDisplayOfTheAccountProtectionAreaInWindowsDefenderSecurityCenter int64 = 1
)

// DisableAppBrowserUI allowed values.
const (
	DisableAppBrowserUIDisableTheUsersCanSeeTheDisplayOfTheAppAndBrowserProtectionAreaInWindowsDefenderSecurityCenter   int64 = 0
	DisableAppBrowserUIEnableTheUsersCannotSeeTheDisplayOfTheAppAndBrowserProtectionAreaInWindowsDefenderSecurityCenter int64 = 1
)

// DisableClearTpmButton allowed values.
const (
	DisableClearTpmButtonDisabledOrNotConfiguredTheSecurityProcessorTroubleshootingPageShowsAButtonThatInitiatesTheProcessToClearTheSecurityProcessorTPM int64 = 0
	DisableClearTpmButtonEnabledTheSecurityProcessorTroubleshootingPageWillNotShowAButtonToInitiateTheProcessToClearTheSecurityProcessorTPM              int64 = 1
)

// DisableDeviceSecurityUI allowed values.
const (
	DisableDeviceSecurityUIDisableTheUsersCanSeeTheDisplayOfTheDeviceSecurityAreaInWindowsDefenderSecurityCenter   int64 = 0
	DisableDeviceSecurityUIEnableTheUsersCannotSeeTheDisplayOfTheDeviceSecurityAreaInWindowsDefenderSecurityCenter int64 = 1
)

// DisableEnhancedNotifications allowed values.
const (
	DisableEnhancedNotificationsDisableWindowsDefenderSecurityCenterWillDisplayCriticalAndNonCriticalNotificationsToUsers      int64 = 0
	DisableEnhancedNotificationsEnableWindowsDefenderSecurityCenterOnlyDisplayNotificationsWhichAreConsideredCriticalOnClients int64 = 1
)

// DisableFamilyUI allowed values.
const (
	DisableFamilyUIDisableTheUsersCanSeeTheDisplayOfTheFamilyOptionsAreaInWindowsDefenderSecurityCenter   int64 = 0
	DisableFamilyUIEnableTheUsersCannotSeeTheDisplayOfTheFamilyOptionsAreaInWindowsDefenderSecurityCenter int64 = 1
)

// DisableHealthUI allowed values.
const (
	DisableHealthUIDisableTheUsersCanSeeTheDisplayOfTheDevicePerformanceAndHealthAreaInWindowsDefenderSecurityCenter   int64 = 0
	DisableHealthUIEnableTheUsersCannotSeeTheDisplayOfTheDevicePerformanceAndHealthAreaInWindowsDefenderSecurityCenter int64 = 1
)

// DisableNetworkUI allowed values.
const (
	DisableNetworkUIDisableTheUsersCanSeeTheDisplayOfTheFirewallAndNetworkProtectionAreaInWindowsDefenderSecurityCenter   int64 = 0
	DisableNetworkUIEnableTheUsersCannotSeeTheDisplayOfTheFirewallAndNetworkProtectionAreaInWindowsDefenderSecurityCenter int64 = 1
)

// DisableNotifications allowed values.
const (
	DisableNotificationsDisableTheUsersCanSeeTheDisplayOfWindowsDefenderSecurityCenterNotifications   int64 = 0
	DisableNotificationsEnableTheUsersCannotSeeTheDisplayOfWindowsDefenderSecurityCenterNotifications int64 = 1
)

// DisableTpmFirmwareUpdateWarning allowed values.
const (
	DisableTpmFirmwareUpdateWarningDisableOrNotConfiguredAWarningWillBeDisplayedIfTheFirmwareOfTheSecurityProcessorTPMShouldBeUpdatedForTPMsThatHaveAVulnerability int64 = 0
	DisableTpmFirmwareUpdateWarningEnabledNoWarningWillBeDisplayedIfTheFirmwareOfTheSecurityProcessorTPMShouldBeUpdated                                            int64 = 1
)

// DisableVirusUI allowed values.
const (
	DisableVirusUIDisableTheUsersCanSeeTheDisplayOfTheVirusAndThreatProtectionAreaInWindowsDefenderSecurityCenter   int64 = 0
	DisableVirusUIEnableTheUsersCannotSeeTheDisplayOfTheVirusAndThreatProtectionAreaInWindowsDefenderSecurityCenter int64 = 1
)

// DisallowExploitProtectionOverride allowed values.
const (
	DisallowExploitProtectionOverrideDisableLocalUsersAreAllowedToMakeChangesInTheExploitProtectionSettingsArea int64 = 0
	DisallowExploitProtectionOverrideEnableLocalUsersCannotMakeChangesInTheExploitProtectionSettingsArea        int64 = 1
)

// EnableCustomizedToasts allowed values.
const (
	EnableCustomizedToastsNotificationText                                          int64 = 0
	EnableCustomizedToastsEnableNotificationsContainTheCompanyNameAndContactOptions int64 = 1
)

// EnableInAppCustomization allowed values.
const (
	EnableInAppCustomizationDisableDoNotDisplayTheCompanyNameAndContactOptionsInTheCardFlyOutNotification int64 = 0
	EnableInAppCustomizationEnableDisplayTheCompanyNameAndContactOptionsInTheCardFlyOutNotification       int64 = 1
)

// HideRansomwareDataRecovery allowed values.
const (
	HideRansomwareDataRecoveryDisableOrNotConfiguredTheRansomwareDataRecoveryAreaWillBeVisible int64 = 0
	HideRansomwareDataRecoveryEnableTheRansomwareDataRecoveryAreaIsHidden                      int64 = 1
)

// HideSecureBoot allowed values.
const (
	HideSecureBootDisableOrNotConfiguredTheSecureBootAreaIsDisplayed int64 = 0
	HideSecureBootEnableTheSecureBootAreaIsHidden                    int64 = 1
)

// HideTPMTroubleshooting allowed values.
const (
	HideTPMTroubleshootingDisableOrNotConfiguredTheSecurityProcessorTPMTroubleshootingAreaIsDisplayed int64 = 0
	HideTPMTroubleshootingEnableTheSecurityProcessorTPMTroubleshootingAreaIsHidden                    int64 = 1
)

// HideWindowsSecurityNotificationAreaControl allowed values.
const (
	HideWindowsSecurityNotificationAreaControlValue0  int64 = 0
	HideWindowsSecurityNotificationAreaControlEnabled int64 = 1
)
