// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

// Package policyadmxfilerevocation binds the ADMX_FileRevocation CSP (./User/Vendor/MSFT/Policy/Config).
package policyadmxfilerevocation
