// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

// Package policyadmxfileservervssprovider binds the ADMX_FileServerVSSProvider CSP (./Device/Vendor/MSFT/Policy/Config).
package policyadmxfileservervssprovider
