// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

// Package policyadmxterminalserver binds the ADMX_TerminalServer CSP (./Device/Vendor/MSFT/Policy/Config).
package policyadmxterminalserver
