// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

package policyadmxuserexperiencevirtualization

import csp "github.com/deploymenttheory/go-bindings-wmi/runtime/csp"

var Calculator = csp.Policy{
	Name:       "Calculator",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/Calculator",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "Calculator", File: "UserExperienceVirtualization.admx"}},
}

var ConfigureSyncMethod = csp.Policy{
	Name:       "ConfigureSyncMethod",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/ConfigureSyncMethod",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV", Name: "ConfigureSyncMethod", File: "UserExperienceVirtualization.admx"}},
}

var ConfigureVdi = csp.Policy{
	Name:       "ConfigureVdi",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/ConfigureVdi",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV", Name: "ConfigureVdi", File: "UserExperienceVirtualization.admx"}},
}

var ContactITDescription = csp.Policy{
	Name:       "ContactITDescription",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/ContactITDescription",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV", Name: "ContactITDescription", File: "UserExperienceVirtualization.admx"}},
}

var ContactITUrl = csp.Policy{
	Name:       "ContactITUrl",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/ContactITUrl",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV", Name: "ContactITUrl", File: "UserExperienceVirtualization.admx"}},
}

var DisableWin8Sync = csp.Policy{
	Name:       "DisableWin8Sync",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/DisableWin8Sync",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV", Name: "DisableWin8Sync", File: "UserExperienceVirtualization.admx"}},
}

var DisableWindowsOSSettings = csp.Policy{
	Name:       "DisableWindowsOSSettings",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/DisableWindowsOSSettings",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV", Name: "DisableWindowsOSSettings", File: "UserExperienceVirtualization.admx"}},
}

var EnableUEV = csp.Policy{
	Name:       "EnableUEV",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/EnableUEV",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV", Name: "EnableUEV", File: "UserExperienceVirtualization.admx"}},
}

var Finance = csp.Policy{
	Name:       "Finance",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/Finance",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Windows8Apps", Name: "Finance", File: "UserExperienceVirtualization.admx"}},
}

var FirstUseNotificationEnabled = csp.Policy{
	Name:       "FirstUseNotificationEnabled",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/FirstUseNotificationEnabled",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV", Name: "FirstUseNotificationEnabled", File: "UserExperienceVirtualization.admx"}},
}

var Games = csp.Policy{
	Name:       "Games",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/Games",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Windows8Apps", Name: "Games", File: "UserExperienceVirtualization.admx"}},
}

var InternetExplorer10 = csp.Policy{
	Name:       "InternetExplorer10",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/InternetExplorer10",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "InternetExplorer10", File: "UserExperienceVirtualization.admx"}},
}

var InternetExplorer11 = csp.Policy{
	Name:       "InternetExplorer11",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/InternetExplorer11",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "InternetExplorer11", File: "UserExperienceVirtualization.admx"}},
}

var InternetExplorer8 = csp.Policy{
	Name:       "InternetExplorer8",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/InternetExplorer8",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "InternetExplorer8", File: "UserExperienceVirtualization.admx"}},
}

var InternetExplorer9 = csp.Policy{
	Name:       "InternetExplorer9",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/InternetExplorer9",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "InternetExplorer9", File: "UserExperienceVirtualization.admx"}},
}

var InternetExplorerCommon = csp.Policy{
	Name:       "InternetExplorerCommon",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/InternetExplorerCommon",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "InternetExplorerCommon", File: "UserExperienceVirtualization.admx"}},
}

var Maps = csp.Policy{
	Name:       "Maps",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/Maps",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Windows8Apps", Name: "Maps", File: "UserExperienceVirtualization.admx"}},
}

var MaxPackageSizeInBytes = csp.Policy{
	Name:       "MaxPackageSizeInBytes",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MaxPackageSizeInBytes",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV", Name: "MaxPackageSizeInBytes", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2010Access = csp.Policy{
	Name:       "MicrosoftOffice2010Access",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2010Access",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2010Access", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2010Common = csp.Policy{
	Name:       "MicrosoftOffice2010Common",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2010Common",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2010Common", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2010Excel = csp.Policy{
	Name:       "MicrosoftOffice2010Excel",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2010Excel",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2010Excel", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2010InfoPath = csp.Policy{
	Name:       "MicrosoftOffice2010InfoPath",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2010InfoPath",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2010InfoPath", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2010Lync = csp.Policy{
	Name:       "MicrosoftOffice2010Lync",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2010Lync",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2010Lync", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2010OneNote = csp.Policy{
	Name:       "MicrosoftOffice2010OneNote",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2010OneNote",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2010OneNote", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2010Outlook = csp.Policy{
	Name:       "MicrosoftOffice2010Outlook",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2010Outlook",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2010Outlook", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2010PowerPoint = csp.Policy{
	Name:       "MicrosoftOffice2010PowerPoint",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2010PowerPoint",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2010PowerPoint", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2010Project = csp.Policy{
	Name:       "MicrosoftOffice2010Project",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2010Project",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2010Project", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2010Publisher = csp.Policy{
	Name:       "MicrosoftOffice2010Publisher",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2010Publisher",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2010Publisher", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2010SharePointDesigner = csp.Policy{
	Name:       "MicrosoftOffice2010SharePointDesigner",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2010SharePointDesigner",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2010SharePointDesigner", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2010SharePointWorkspace = csp.Policy{
	Name:       "MicrosoftOffice2010SharePointWorkspace",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2010SharePointWorkspace",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2010SharePointWorkspace", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2010Visio = csp.Policy{
	Name:       "MicrosoftOffice2010Visio",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2010Visio",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2010Visio", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2010Word = csp.Policy{
	Name:       "MicrosoftOffice2010Word",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2010Word",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2010Word", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013Access = csp.Policy{
	Name:       "MicrosoftOffice2013Access",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013Access",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013Access", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013AccessBackup = csp.Policy{
	Name:       "MicrosoftOffice2013AccessBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013AccessBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013AccessBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013Common = csp.Policy{
	Name:       "MicrosoftOffice2013Common",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013Common",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013Common", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013CommonBackup = csp.Policy{
	Name:       "MicrosoftOffice2013CommonBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013CommonBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013CommonBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013Excel = csp.Policy{
	Name:       "MicrosoftOffice2013Excel",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013Excel",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013Excel", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013ExcelBackup = csp.Policy{
	Name:       "MicrosoftOffice2013ExcelBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013ExcelBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013ExcelBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013InfoPath = csp.Policy{
	Name:       "MicrosoftOffice2013InfoPath",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013InfoPath",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013InfoPath", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013InfoPathBackup = csp.Policy{
	Name:       "MicrosoftOffice2013InfoPathBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013InfoPathBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013InfoPathBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013Lync = csp.Policy{
	Name:       "MicrosoftOffice2013Lync",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013Lync",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013Lync", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013LyncBackup = csp.Policy{
	Name:       "MicrosoftOffice2013LyncBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013LyncBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013LyncBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013OneDriveForBusiness = csp.Policy{
	Name:       "MicrosoftOffice2013OneDriveForBusiness",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013OneDriveForBusiness",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013OneDriveForBusiness", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013OneNote = csp.Policy{
	Name:       "MicrosoftOffice2013OneNote",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013OneNote",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013OneNote", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013OneNoteBackup = csp.Policy{
	Name:       "MicrosoftOffice2013OneNoteBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013OneNoteBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013OneNoteBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013Outlook = csp.Policy{
	Name:       "MicrosoftOffice2013Outlook",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013Outlook",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013Outlook", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013OutlookBackup = csp.Policy{
	Name:       "MicrosoftOffice2013OutlookBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013OutlookBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013OutlookBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013PowerPoint = csp.Policy{
	Name:       "MicrosoftOffice2013PowerPoint",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013PowerPoint",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013PowerPoint", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013PowerPointBackup = csp.Policy{
	Name:       "MicrosoftOffice2013PowerPointBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013PowerPointBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013PowerPointBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013Project = csp.Policy{
	Name:       "MicrosoftOffice2013Project",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013Project",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013Project", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013ProjectBackup = csp.Policy{
	Name:       "MicrosoftOffice2013ProjectBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013ProjectBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013ProjectBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013Publisher = csp.Policy{
	Name:       "MicrosoftOffice2013Publisher",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013Publisher",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013Publisher", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013PublisherBackup = csp.Policy{
	Name:       "MicrosoftOffice2013PublisherBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013PublisherBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013PublisherBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013SharePointDesigner = csp.Policy{
	Name:       "MicrosoftOffice2013SharePointDesigner",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013SharePointDesigner",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013SharePointDesigner", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013SharePointDesignerBackup = csp.Policy{
	Name:       "MicrosoftOffice2013SharePointDesignerBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013SharePointDesignerBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013SharePointDesignerBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013UploadCenter = csp.Policy{
	Name:       "MicrosoftOffice2013UploadCenter",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013UploadCenter",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013UploadCenter", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013Visio = csp.Policy{
	Name:       "MicrosoftOffice2013Visio",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013Visio",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013Visio", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013VisioBackup = csp.Policy{
	Name:       "MicrosoftOffice2013VisioBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013VisioBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013VisioBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013Word = csp.Policy{
	Name:       "MicrosoftOffice2013Word",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013Word",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013Word", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2013WordBackup = csp.Policy{
	Name:       "MicrosoftOffice2013WordBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2013WordBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2013WordBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016Access = csp.Policy{
	Name:       "MicrosoftOffice2016Access",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016Access",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016Access", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016AccessBackup = csp.Policy{
	Name:       "MicrosoftOffice2016AccessBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016AccessBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016AccessBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016Common = csp.Policy{
	Name:       "MicrosoftOffice2016Common",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016Common",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016Common", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016CommonBackup = csp.Policy{
	Name:       "MicrosoftOffice2016CommonBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016CommonBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016CommonBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016Excel = csp.Policy{
	Name:       "MicrosoftOffice2016Excel",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016Excel",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016Excel", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016ExcelBackup = csp.Policy{
	Name:       "MicrosoftOffice2016ExcelBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016ExcelBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016ExcelBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016Lync = csp.Policy{
	Name:       "MicrosoftOffice2016Lync",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016Lync",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016Lync", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016LyncBackup = csp.Policy{
	Name:       "MicrosoftOffice2016LyncBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016LyncBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016LyncBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016OneDriveForBusiness = csp.Policy{
	Name:       "MicrosoftOffice2016OneDriveForBusiness",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016OneDriveForBusiness",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016OneDriveForBusiness", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016OneNote = csp.Policy{
	Name:       "MicrosoftOffice2016OneNote",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016OneNote",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016OneNote", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016OneNoteBackup = csp.Policy{
	Name:       "MicrosoftOffice2016OneNoteBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016OneNoteBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016OneNoteBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016Outlook = csp.Policy{
	Name:       "MicrosoftOffice2016Outlook",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016Outlook",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016Outlook", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016OutlookBackup = csp.Policy{
	Name:       "MicrosoftOffice2016OutlookBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016OutlookBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016OutlookBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016PowerPoint = csp.Policy{
	Name:       "MicrosoftOffice2016PowerPoint",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016PowerPoint",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016PowerPoint", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016PowerPointBackup = csp.Policy{
	Name:       "MicrosoftOffice2016PowerPointBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016PowerPointBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016PowerPointBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016Project = csp.Policy{
	Name:       "MicrosoftOffice2016Project",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016Project",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016Project", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016ProjectBackup = csp.Policy{
	Name:       "MicrosoftOffice2016ProjectBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016ProjectBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016ProjectBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016Publisher = csp.Policy{
	Name:       "MicrosoftOffice2016Publisher",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016Publisher",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016Publisher", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016PublisherBackup = csp.Policy{
	Name:       "MicrosoftOffice2016PublisherBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016PublisherBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016PublisherBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016UploadCenter = csp.Policy{
	Name:       "MicrosoftOffice2016UploadCenter",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016UploadCenter",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016UploadCenter", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016Visio = csp.Policy{
	Name:       "MicrosoftOffice2016Visio",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016Visio",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016Visio", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016VisioBackup = csp.Policy{
	Name:       "MicrosoftOffice2016VisioBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016VisioBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016VisioBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016Word = csp.Policy{
	Name:       "MicrosoftOffice2016Word",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016Word",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016Word", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice2016WordBackup = csp.Policy{
	Name:       "MicrosoftOffice2016WordBackup",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice2016WordBackup",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice2016WordBackup", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365Access2013 = csp.Policy{
	Name:       "MicrosoftOffice365Access2013",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365Access2013",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365Access2013", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365Access2016 = csp.Policy{
	Name:       "MicrosoftOffice365Access2016",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365Access2016",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365Access2016", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365Common2013 = csp.Policy{
	Name:       "MicrosoftOffice365Common2013",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365Common2013",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365Common2013", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365Common2016 = csp.Policy{
	Name:       "MicrosoftOffice365Common2016",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365Common2016",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365Common2016", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365Excel2013 = csp.Policy{
	Name:       "MicrosoftOffice365Excel2013",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365Excel2013",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365Excel2013", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365Excel2016 = csp.Policy{
	Name:       "MicrosoftOffice365Excel2016",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365Excel2016",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365Excel2016", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365InfoPath2013 = csp.Policy{
	Name:       "MicrosoftOffice365InfoPath2013",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365InfoPath2013",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365InfoPath2013", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365Lync2013 = csp.Policy{
	Name:       "MicrosoftOffice365Lync2013",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365Lync2013",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365Lync2013", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365Lync2016 = csp.Policy{
	Name:       "MicrosoftOffice365Lync2016",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365Lync2016",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365Lync2016", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365OneNote2013 = csp.Policy{
	Name:       "MicrosoftOffice365OneNote2013",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365OneNote2013",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365OneNote2013", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365OneNote2016 = csp.Policy{
	Name:       "MicrosoftOffice365OneNote2016",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365OneNote2016",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365OneNote2016", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365Outlook2013 = csp.Policy{
	Name:       "MicrosoftOffice365Outlook2013",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365Outlook2013",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365Outlook2013", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365Outlook2016 = csp.Policy{
	Name:       "MicrosoftOffice365Outlook2016",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365Outlook2016",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365Outlook2016", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365PowerPoint2013 = csp.Policy{
	Name:       "MicrosoftOffice365PowerPoint2013",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365PowerPoint2013",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365PowerPoint2013", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365PowerPoint2016 = csp.Policy{
	Name:       "MicrosoftOffice365PowerPoint2016",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365PowerPoint2016",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365PowerPoint2016", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365Project2013 = csp.Policy{
	Name:       "MicrosoftOffice365Project2013",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365Project2013",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365Project2013", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365Project2016 = csp.Policy{
	Name:       "MicrosoftOffice365Project2016",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365Project2016",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365Project2016", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365Publisher2013 = csp.Policy{
	Name:       "MicrosoftOffice365Publisher2013",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365Publisher2013",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365Publisher2013", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365Publisher2016 = csp.Policy{
	Name:       "MicrosoftOffice365Publisher2016",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365Publisher2016",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365Publisher2016", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365SharePointDesigner2013 = csp.Policy{
	Name:       "MicrosoftOffice365SharePointDesigner2013",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365SharePointDesigner2013",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365SharePointDesigner2013", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365Visio2013 = csp.Policy{
	Name:       "MicrosoftOffice365Visio2013",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365Visio2013",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365Visio2013", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365Visio2016 = csp.Policy{
	Name:       "MicrosoftOffice365Visio2016",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365Visio2016",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365Visio2016", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365Word2013 = csp.Policy{
	Name:       "MicrosoftOffice365Word2013",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365Word2013",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365Word2013", File: "UserExperienceVirtualization.admx"}},
}

var MicrosoftOffice365Word2016 = csp.Policy{
	Name:       "MicrosoftOffice365Word2016",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/MicrosoftOffice365Word2016",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "MicrosoftOffice365Word2016", File: "UserExperienceVirtualization.admx"}},
}

var Music = csp.Policy{
	Name:       "Music",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/Music",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Windows8Apps", Name: "Music", File: "UserExperienceVirtualization.admx"}},
}

var News = csp.Policy{
	Name:       "News",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/News",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Windows8Apps", Name: "News", File: "UserExperienceVirtualization.admx"}},
}

var Notepad = csp.Policy{
	Name:       "Notepad",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/Notepad",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "Notepad", File: "UserExperienceVirtualization.admx"}},
}

var Reader = csp.Policy{
	Name:       "Reader",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/Reader",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Windows8Apps", Name: "Reader", File: "UserExperienceVirtualization.admx"}},
}

var RepositoryTimeout = csp.Policy{
	Name:       "RepositoryTimeout",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/RepositoryTimeout",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV", Name: "RepositoryTimeout", File: "UserExperienceVirtualization.admx"}},
}

var SettingsStoragePath = csp.Policy{
	Name:       "SettingsStoragePath",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/SettingsStoragePath",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV", Name: "SettingsStoragePath", File: "UserExperienceVirtualization.admx"}},
}

var SettingsTemplateCatalogPath = csp.Policy{
	Name:       "SettingsTemplateCatalogPath",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/SettingsTemplateCatalogPath",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV", Name: "SettingsTemplateCatalogPath", File: "UserExperienceVirtualization.admx"}},
}

var Sports = csp.Policy{
	Name:       "Sports",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/Sports",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Windows8Apps", Name: "Sports", File: "UserExperienceVirtualization.admx"}},
}

var SyncEnabled = csp.Policy{
	Name:       "SyncEnabled",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/SyncEnabled",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV", Name: "SyncEnabled", File: "UserExperienceVirtualization.admx"}},
}

var SyncOverMeteredNetwork = csp.Policy{
	Name:       "SyncOverMeteredNetwork",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/SyncOverMeteredNetwork",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV", Name: "SyncOverMeteredNetwork", File: "UserExperienceVirtualization.admx"}},
}

var SyncOverMeteredNetworkWhenRoaming = csp.Policy{
	Name:       "SyncOverMeteredNetworkWhenRoaming",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/SyncOverMeteredNetworkWhenRoaming",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV", Name: "SyncOverMeteredNetworkWhenRoaming", File: "UserExperienceVirtualization.admx"}},
}

var SyncProviderPingEnabled = csp.Policy{
	Name:       "SyncProviderPingEnabled",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/SyncProviderPingEnabled",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV", Name: "SyncProviderPingEnabled", File: "UserExperienceVirtualization.admx"}},
}

var SyncUnlistedWindows8Apps = csp.Policy{
	Name:       "SyncUnlistedWindows8Apps",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/SyncUnlistedWindows8Apps",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV", Name: "SyncUnlistedWindows8Apps", File: "UserExperienceVirtualization.admx"}},
}

var Travel = csp.Policy{
	Name:       "Travel",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/Travel",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Windows8Apps", Name: "Travel", File: "UserExperienceVirtualization.admx"}},
}

var TrayIconEnabled = csp.Policy{
	Name:       "TrayIconEnabled",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/TrayIconEnabled",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV", Name: "TrayIconEnabled", File: "UserExperienceVirtualization.admx"}},
}

var Video = csp.Policy{
	Name:       "Video",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/Video",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Windows8Apps", Name: "Video", File: "UserExperienceVirtualization.admx"}},
}

var Weather = csp.Policy{
	Name:       "Weather",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/Weather",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Windows8Apps", Name: "Weather", File: "UserExperienceVirtualization.admx"}},
}

var Wordpad = csp.Policy{
	Name:       "Wordpad",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_UserExperienceVirtualization/Wordpad",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "UserExperienceVirtualization~AT~WindowsComponents~UEV~Applications", Name: "Wordpad", File: "UserExperienceVirtualization.admx"}},
}

// All lists every policy in this CSP area.
var All = []csp.Policy{
	Calculator,
	ConfigureSyncMethod,
	ConfigureVdi,
	ContactITDescription,
	ContactITUrl,
	DisableWin8Sync,
	DisableWindowsOSSettings,
	EnableUEV,
	Finance,
	FirstUseNotificationEnabled,
	Games,
	InternetExplorer10,
	InternetExplorer11,
	InternetExplorer8,
	InternetExplorer9,
	InternetExplorerCommon,
	Maps,
	MaxPackageSizeInBytes,
	MicrosoftOffice2010Access,
	MicrosoftOffice2010Common,
	MicrosoftOffice2010Excel,
	MicrosoftOffice2010InfoPath,
	MicrosoftOffice2010Lync,
	MicrosoftOffice2010OneNote,
	MicrosoftOffice2010Outlook,
	MicrosoftOffice2010PowerPoint,
	MicrosoftOffice2010Project,
	MicrosoftOffice2010Publisher,
	MicrosoftOffice2010SharePointDesigner,
	MicrosoftOffice2010SharePointWorkspace,
	MicrosoftOffice2010Visio,
	MicrosoftOffice2010Word,
	MicrosoftOffice2013Access,
	MicrosoftOffice2013AccessBackup,
	MicrosoftOffice2013Common,
	MicrosoftOffice2013CommonBackup,
	MicrosoftOffice2013Excel,
	MicrosoftOffice2013ExcelBackup,
	MicrosoftOffice2013InfoPath,
	MicrosoftOffice2013InfoPathBackup,
	MicrosoftOffice2013Lync,
	MicrosoftOffice2013LyncBackup,
	MicrosoftOffice2013OneDriveForBusiness,
	MicrosoftOffice2013OneNote,
	MicrosoftOffice2013OneNoteBackup,
	MicrosoftOffice2013Outlook,
	MicrosoftOffice2013OutlookBackup,
	MicrosoftOffice2013PowerPoint,
	MicrosoftOffice2013PowerPointBackup,
	MicrosoftOffice2013Project,
	MicrosoftOffice2013ProjectBackup,
	MicrosoftOffice2013Publisher,
	MicrosoftOffice2013PublisherBackup,
	MicrosoftOffice2013SharePointDesigner,
	MicrosoftOffice2013SharePointDesignerBackup,
	MicrosoftOffice2013UploadCenter,
	MicrosoftOffice2013Visio,
	MicrosoftOffice2013VisioBackup,
	MicrosoftOffice2013Word,
	MicrosoftOffice2013WordBackup,
	MicrosoftOffice2016Access,
	MicrosoftOffice2016AccessBackup,
	MicrosoftOffice2016Common,
	MicrosoftOffice2016CommonBackup,
	MicrosoftOffice2016Excel,
	MicrosoftOffice2016ExcelBackup,
	MicrosoftOffice2016Lync,
	MicrosoftOffice2016LyncBackup,
	MicrosoftOffice2016OneDriveForBusiness,
	MicrosoftOffice2016OneNote,
	MicrosoftOffice2016OneNoteBackup,
	MicrosoftOffice2016Outlook,
	MicrosoftOffice2016OutlookBackup,
	MicrosoftOffice2016PowerPoint,
	MicrosoftOffice2016PowerPointBackup,
	MicrosoftOffice2016Project,
	MicrosoftOffice2016ProjectBackup,
	MicrosoftOffice2016Publisher,
	MicrosoftOffice2016PublisherBackup,
	MicrosoftOffice2016UploadCenter,
	MicrosoftOffice2016Visio,
	MicrosoftOffice2016VisioBackup,
	MicrosoftOffice2016Word,
	MicrosoftOffice2016WordBackup,
	MicrosoftOffice365Access2013,
	MicrosoftOffice365Access2016,
	MicrosoftOffice365Common2013,
	MicrosoftOffice365Common2016,
	MicrosoftOffice365Excel2013,
	MicrosoftOffice365Excel2016,
	MicrosoftOffice365InfoPath2013,
	MicrosoftOffice365Lync2013,
	MicrosoftOffice365Lync2016,
	MicrosoftOffice365OneNote2013,
	MicrosoftOffice365OneNote2016,
	MicrosoftOffice365Outlook2013,
	MicrosoftOffice365Outlook2016,
	MicrosoftOffice365PowerPoint2013,
	MicrosoftOffice365PowerPoint2016,
	MicrosoftOffice365Project2013,
	MicrosoftOffice365Project2016,
	MicrosoftOffice365Publisher2013,
	MicrosoftOffice365Publisher2016,
	MicrosoftOffice365SharePointDesigner2013,
	MicrosoftOffice365Visio2013,
	MicrosoftOffice365Visio2016,
	MicrosoftOffice365Word2013,
	MicrosoftOffice365Word2016,
	Music,
	News,
	Notepad,
	Reader,
	RepositoryTimeout,
	SettingsStoragePath,
	SettingsTemplateCatalogPath,
	Sports,
	SyncEnabled,
	SyncOverMeteredNetwork,
	SyncOverMeteredNetworkWhenRoaming,
	SyncProviderPingEnabled,
	SyncUnlistedWindows8Apps,
	Travel,
	TrayIconEnabled,
	Video,
	Weather,
	Wordpad,
}
