// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

package policyeap

// AllowTLS13 allowed values.
const (
	AllowTLS13UseOfTLSVersion13IsNotAllowedForAuthentication int64 = 0
	AllowTLS13UseOfTLSVersion13IsAllowedForAuthentication    int64 = 1
)
