// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

package policyadmxdesktop

import csp "github.com/deploymenttheory/go-bindings-wmi/runtime/csp"

var ADEnableFilter = csp.Policy{
	Name:       "AD_EnableFilter",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/AD_EnableFilter",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop~ActiveDirectory", Name: "AD_EnableFilter", File: "Desktop.admx"}},
}

var ADHideDirectoryFolder = csp.Policy{
	Name:       "AD_HideDirectoryFolder",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/AD_HideDirectoryFolder",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop~ActiveDirectory", Name: "AD_HideDirectoryFolder", File: "Desktop.admx"}},
}

var ADQueryLimit = csp.Policy{
	Name:       "AD_QueryLimit",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/AD_QueryLimit",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop~ActiveDirectory", Name: "AD_QueryLimit", File: "Desktop.admx"}},
}

var EnableThemeFileRemoteResource = csp.Policy{
	Name:       "EnableThemeFileRemoteResource",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/EnableThemeFileRemoteResource",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22621",
	CSPVersion: "11.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop", Name: "EnableThemeFileRemoteResource", File: "Desktop.admx"}},
}

var ForceActiveDesktopOn = csp.Policy{
	Name:       "ForceActiveDesktopOn",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/ForceActiveDesktopOn",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop~ActiveDesktop", Name: "ForceActiveDesktopOn", File: "Desktop.admx"}},
}

var NoActiveDesktop = csp.Policy{
	Name:       "NoActiveDesktop",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/NoActiveDesktop",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop~ActiveDesktop", Name: "NoActiveDesktop", File: "Desktop.admx"}},
}

var NoActiveDesktopChanges = csp.Policy{
	Name:       "NoActiveDesktopChanges",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/NoActiveDesktopChanges",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop~ActiveDesktop", Name: "NoActiveDesktopChanges", File: "Desktop.admx"}},
}

var NoDesktop = csp.Policy{
	Name:       "NoDesktop",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/NoDesktop",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop", Name: "NoDesktop", File: "Desktop.admx"}},
}

var NoDesktopCleanupWizard = csp.Policy{
	Name:       "NoDesktopCleanupWizard",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/NoDesktopCleanupWizard",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop", Name: "NoDesktopCleanupWizard", File: "Desktop.admx"}},
}

var NoInternetIcon = csp.Policy{
	Name:       "NoInternetIcon",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/NoInternetIcon",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop", Name: "NoInternetIcon", File: "Desktop.admx"}},
}

var NoMyComputerIcon = csp.Policy{
	Name:       "NoMyComputerIcon",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/NoMyComputerIcon",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop", Name: "NoMyComputerIcon", File: "Desktop.admx"}},
}

var NoMyDocumentsIcon = csp.Policy{
	Name:       "NoMyDocumentsIcon",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/NoMyDocumentsIcon",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop", Name: "NoMyDocumentsIcon", File: "Desktop.admx"}},
}

var NoNetHood = csp.Policy{
	Name:       "NoNetHood",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/NoNetHood",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop", Name: "NoNetHood", File: "Desktop.admx"}},
}

var NoPropertiesMyComputer = csp.Policy{
	Name:       "NoPropertiesMyComputer",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/NoPropertiesMyComputer",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop", Name: "NoPropertiesMyComputer", File: "Desktop.admx"}},
}

var NoPropertiesMyDocuments = csp.Policy{
	Name:       "NoPropertiesMyDocuments",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/NoPropertiesMyDocuments",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop", Name: "NoPropertiesMyDocuments", File: "Desktop.admx"}},
}

var NoRecentDocsNetHood = csp.Policy{
	Name:       "NoRecentDocsNetHood",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/NoRecentDocsNetHood",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop", Name: "NoRecentDocsNetHood", File: "Desktop.admx"}},
}

var NoRecycleBinIcon = csp.Policy{
	Name:       "NoRecycleBinIcon",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/NoRecycleBinIcon",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop", Name: "NoRecycleBinIcon", File: "Desktop.admx"}},
}

var NoRecycleBinProperties = csp.Policy{
	Name:       "NoRecycleBinProperties",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/NoRecycleBinProperties",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop", Name: "NoRecycleBinProperties", File: "Desktop.admx"}},
}

var NoSaveSettings = csp.Policy{
	Name:       "NoSaveSettings",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/NoSaveSettings",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop", Name: "NoSaveSettings", File: "Desktop.admx"}},
}

var NoWindowMinimizingShortcuts = csp.Policy{
	Name:       "NoWindowMinimizingShortcuts",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/NoWindowMinimizingShortcuts",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop", Name: "NoWindowMinimizingShortcuts", File: "Desktop.admx"}},
}

var Wallpaper = csp.Policy{
	Name:       "Wallpaper",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/Wallpaper",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop~ActiveDesktop", Name: "Wallpaper", File: "Desktop.admx"}},
}

var SzATCDisableAdd = csp.Policy{
	Name:       "sz_ATC_DisableAdd",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/sz_ATC_DisableAdd",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop~ActiveDesktop", Name: "sz_ATC_DisableAdd", File: "Desktop.admx"}},
}

var SzATCDisableClose = csp.Policy{
	Name:       "sz_ATC_DisableClose",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/sz_ATC_DisableClose",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop~ActiveDesktop", Name: "sz_ATC_DisableClose", File: "Desktop.admx"}},
}

var SzATCDisableDel = csp.Policy{
	Name:       "sz_ATC_DisableDel",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/sz_ATC_DisableDel",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop~ActiveDesktop", Name: "sz_ATC_DisableDel", File: "Desktop.admx"}},
}

var SzATCDisableEdit = csp.Policy{
	Name:       "sz_ATC_DisableEdit",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/sz_ATC_DisableEdit",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop~ActiveDesktop", Name: "sz_ATC_DisableEdit", File: "Desktop.admx"}},
}

var SzATCNoComponents = csp.Policy{
	Name:       "sz_ATC_NoComponents",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/sz_ATC_NoComponents",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop~ActiveDesktop", Name: "sz_ATC_NoComponents", File: "Desktop.admx"}},
}

var SzAdminComponentsTitle = csp.Policy{
	Name:       "sz_AdminComponents_Title",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/sz_AdminComponents_Title",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop~ActiveDesktop", Name: "sz_AdminComponents_Title", File: "Desktop.admx"}},
}

var SzDBDragDropClose = csp.Policy{
	Name:       "sz_DB_DragDropClose",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/sz_DB_DragDropClose",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop", Name: "sz_DB_DragDropClose", File: "Desktop.admx"}},
}

var SzDBMoving = csp.Policy{
	Name:       "sz_DB_Moving",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/sz_DB_Moving",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop", Name: "sz_DB_Moving", File: "Desktop.admx"}},
}

var SzDWPNoHTMLPaper = csp.Policy{
	Name:       "sz_DWP_NoHTMLPaper",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_Desktop/sz_DWP_NoHTMLPaper",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "Desktop~AT~Desktop~ActiveDesktop", Name: "sz_DWP_NoHTMLPaper", File: "Desktop.admx"}},
}

// All lists every policy in this CSP area.
var All = []csp.Policy{
	ADEnableFilter,
	ADHideDirectoryFolder,
	ADQueryLimit,
	EnableThemeFileRemoteResource,
	ForceActiveDesktopOn,
	NoActiveDesktop,
	NoActiveDesktopChanges,
	NoDesktop,
	NoDesktopCleanupWizard,
	NoInternetIcon,
	NoMyComputerIcon,
	NoMyDocumentsIcon,
	NoNetHood,
	NoPropertiesMyComputer,
	NoPropertiesMyDocuments,
	NoRecentDocsNetHood,
	NoRecycleBinIcon,
	NoRecycleBinProperties,
	NoSaveSettings,
	NoWindowMinimizingShortcuts,
	Wallpaper,
	SzATCDisableAdd,
	SzATCDisableClose,
	SzATCDisableDel,
	SzATCDisableEdit,
	SzATCNoComponents,
	SzAdminComponentsTitle,
	SzDBDragDropClose,
	SzDBMoving,
	SzDWPNoHTMLPaper,
}
