// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

// Package policyadmxsystemrestore binds the ADMX_SystemRestore CSP (./Device/Vendor/MSFT/Policy/Config).
package policyadmxsystemrestore
