// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

//go:build windows

package policyremoteshell

import (
	csp "github.com/deploymenttheory/go-bindings-wmi/runtime/csp"
	wmi "github.com/deploymenttheory/go-bindings-wmi/runtime/wmi"
)

// Service drives this CSP area's policies through the MDM bridge.
// Construct it with New, passing a wmi.Service connected to the bridge
// namespace (csp.Connect, which requires the SYSTEM account).
type Service struct{ svc *wmi.Service }

// New returns a Service bound to a connected bridge session.
func New(svc *wmi.Service) *Service { return &Service{svc: svc} }

// GetAllowRemoteShellAccess reads the effective value of AllowRemoteShellAccess.
func (s *Service) GetAllowRemoteShellAccess() (string, error) {
	v, err := csp.Read(s.svc, AllowRemoteShellAccess)
	if err != nil {
		return "", err
	}
	return wmi.AsString(v), nil
}

// SetAllowRemoteShellAccess sets AllowRemoteShellAccess (OMA-DM Add/Replace).
func (s *Service) SetAllowRemoteShellAccess(v string) error {
	return csp.Set(s.svc, AllowRemoteShellAccess, v)
}

// DeleteAllowRemoteShellAccess unmanages AllowRemoteShellAccess (OMA-DM Delete).
func (s *Service) DeleteAllowRemoteShellAccess() error {
	return csp.Delete(s.svc, AllowRemoteShellAccess)
}

// GetMaxConcurrentUsers reads the effective value of MaxConcurrentUsers.
func (s *Service) GetMaxConcurrentUsers() (string, error) {
	v, err := csp.Read(s.svc, MaxConcurrentUsers)
	if err != nil {
		return "", err
	}
	return wmi.AsString(v), nil
}

// SetMaxConcurrentUsers sets MaxConcurrentUsers (OMA-DM Add/Replace).
func (s *Service) SetMaxConcurrentUsers(v string) error { return csp.Set(s.svc, MaxConcurrentUsers, v) }

// DeleteMaxConcurrentUsers unmanages MaxConcurrentUsers (OMA-DM Delete).
func (s *Service) DeleteMaxConcurrentUsers() error { return csp.Delete(s.svc, MaxConcurrentUsers) }

// GetSpecifyIdleTimeout reads the effective value of SpecifyIdleTimeout.
func (s *Service) GetSpecifyIdleTimeout() (string, error) {
	v, err := csp.Read(s.svc, SpecifyIdleTimeout)
	if err != nil {
		return "", err
	}
	return wmi.AsString(v), nil
}

// SetSpecifyIdleTimeout sets SpecifyIdleTimeout (OMA-DM Add/Replace).
func (s *Service) SetSpecifyIdleTimeout(v string) error { return csp.Set(s.svc, SpecifyIdleTimeout, v) }

// DeleteSpecifyIdleTimeout unmanages SpecifyIdleTimeout (OMA-DM Delete).
func (s *Service) DeleteSpecifyIdleTimeout() error { return csp.Delete(s.svc, SpecifyIdleTimeout) }

// GetSpecifyMaxMemory reads the effective value of SpecifyMaxMemory.
func (s *Service) GetSpecifyMaxMemory() (string, error) {
	v, err := csp.Read(s.svc, SpecifyMaxMemory)
	if err != nil {
		return "", err
	}
	return wmi.AsString(v), nil
}

// SetSpecifyMaxMemory sets SpecifyMaxMemory (OMA-DM Add/Replace).
func (s *Service) SetSpecifyMaxMemory(v string) error { return csp.Set(s.svc, SpecifyMaxMemory, v) }

// DeleteSpecifyMaxMemory unmanages SpecifyMaxMemory (OMA-DM Delete).
func (s *Service) DeleteSpecifyMaxMemory() error { return csp.Delete(s.svc, SpecifyMaxMemory) }

// GetSpecifyMaxProcesses reads the effective value of SpecifyMaxProcesses.
func (s *Service) GetSpecifyMaxProcesses() (string, error) {
	v, err := csp.Read(s.svc, SpecifyMaxProcesses)
	if err != nil {
		return "", err
	}
	return wmi.AsString(v), nil
}

// SetSpecifyMaxProcesses sets SpecifyMaxProcesses (OMA-DM Add/Replace).
func (s *Service) SetSpecifyMaxProcesses(v string) error {
	return csp.Set(s.svc, SpecifyMaxProcesses, v)
}

// DeleteSpecifyMaxProcesses unmanages SpecifyMaxProcesses (OMA-DM Delete).
func (s *Service) DeleteSpecifyMaxProcesses() error { return csp.Delete(s.svc, SpecifyMaxProcesses) }

// GetSpecifyMaxRemoteShells reads the effective value of SpecifyMaxRemoteShells.
func (s *Service) GetSpecifyMaxRemoteShells() (string, error) {
	v, err := csp.Read(s.svc, SpecifyMaxRemoteShells)
	if err != nil {
		return "", err
	}
	return wmi.AsString(v), nil
}

// SetSpecifyMaxRemoteShells sets SpecifyMaxRemoteShells (OMA-DM Add/Replace).
func (s *Service) SetSpecifyMaxRemoteShells(v string) error {
	return csp.Set(s.svc, SpecifyMaxRemoteShells, v)
}

// DeleteSpecifyMaxRemoteShells unmanages SpecifyMaxRemoteShells (OMA-DM Delete).
func (s *Service) DeleteSpecifyMaxRemoteShells() error {
	return csp.Delete(s.svc, SpecifyMaxRemoteShells)
}

// GetSpecifyShellTimeout reads the effective value of SpecifyShellTimeout.
func (s *Service) GetSpecifyShellTimeout() (string, error) {
	v, err := csp.Read(s.svc, SpecifyShellTimeout)
	if err != nil {
		return "", err
	}
	return wmi.AsString(v), nil
}

// SetSpecifyShellTimeout sets SpecifyShellTimeout (OMA-DM Add/Replace).
func (s *Service) SetSpecifyShellTimeout(v string) error {
	return csp.Set(s.svc, SpecifyShellTimeout, v)
}

// DeleteSpecifyShellTimeout unmanages SpecifyShellTimeout (OMA-DM Delete).
func (s *Service) DeleteSpecifyShellTimeout() error { return csp.Delete(s.svc, SpecifyShellTimeout) }
