// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

//go:build windows

package policycredentialsdelegation

import (
	csp "github.com/deploymenttheory/go-bindings-wmi/runtime/csp"
	wmi "github.com/deploymenttheory/go-bindings-wmi/runtime/wmi"
)

// Service drives this CSP area's policies through the MDM bridge.
// Construct it with New, passing a wmi.Service connected to the bridge
// namespace (csp.Connect, which requires the SYSTEM account).
type Service struct{ svc *wmi.Service }

// New returns a Service bound to a connected bridge session.
func New(svc *wmi.Service) *Service { return &Service{svc: svc} }

// GetRemoteHostAllowsDelegationOfNonExportableCredentials reads the effective value of RemoteHostAllowsDelegationOfNonExportableCredentials.
func (s *Service) GetRemoteHostAllowsDelegationOfNonExportableCredentials() (string, error) {
	v, err := csp.Read(s.svc, RemoteHostAllowsDelegationOfNonExportableCredentials)
	if err != nil {
		return "", err
	}
	return wmi.AsString(v), nil
}

// SetRemoteHostAllowsDelegationOfNonExportableCredentials sets RemoteHostAllowsDelegationOfNonExportableCredentials (OMA-DM Add/Replace).
func (s *Service) SetRemoteHostAllowsDelegationOfNonExportableCredentials(v string) error {
	return csp.Set(s.svc, RemoteHostAllowsDelegationOfNonExportableCredentials, v)
}

// DeleteRemoteHostAllowsDelegationOfNonExportableCredentials unmanages RemoteHostAllowsDelegationOfNonExportableCredentials (OMA-DM Delete).
func (s *Service) DeleteRemoteHostAllowsDelegationOfNonExportableCredentials() error {
	return csp.Delete(s.svc, RemoteHostAllowsDelegationOfNonExportableCredentials)
}
