// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

package policystart

// AllowPinnedFolderDocuments allowed values.
const (
	AllowPinnedFolderDocumentsTheShortcutIsHiddenAndDisablesTheSettingInTheSettingsApp         int64 = 0
	AllowPinnedFolderDocumentsTheShortcutIsVisibleAndDisablesTheSettingInTheSettingsApp        int64 = 1
	AllowPinnedFolderDocumentsThereIsNoEnforcedConfigurationAndTheSettingCanBeChangedByTheUser int64 = 65535
)

// AllowPinnedFolderDownloads allowed values.
const (
	AllowPinnedFolderDownloadsTheShortcutIsHiddenAndDisablesTheSettingInTheSettingsApp         int64 = 0
	AllowPinnedFolderDownloadsTheShortcutIsVisibleAndDisablesTheSettingInTheSettingsApp        int64 = 1
	AllowPinnedFolderDownloadsThereIsNoEnforcedConfigurationAndTheSettingCanBeChangedByTheUser int64 = 65535
)

// AllowPinnedFolderFileExplorer allowed values.
const (
	AllowPinnedFolderFileExplorerTheShortcutIsHiddenAndDisablesTheSettingInTheSettingsApp         int64 = 0
	AllowPinnedFolderFileExplorerTheShortcutIsVisibleAndDisablesTheSettingInTheSettingsApp        int64 = 1
	AllowPinnedFolderFileExplorerThereIsNoEnforcedConfigurationAndTheSettingCanBeChangedByTheUser int64 = 65535
)

// AllowPinnedFolderHomeGroup allowed values.
const (
	AllowPinnedFolderHomeGroupTheShortcutIsHiddenAndDisablesTheSettingInTheSettingsApp         int64 = 0
	AllowPinnedFolderHomeGroupTheShortcutIsVisibleAndDisablesTheSettingInTheSettingsApp        int64 = 1
	AllowPinnedFolderHomeGroupThereIsNoEnforcedConfigurationAndTheSettingCanBeChangedByTheUser int64 = 65535
)

// AllowPinnedFolderMusic allowed values.
const (
	AllowPinnedFolderMusicTheShortcutIsHiddenAndDisablesTheSettingInTheSettingsApp         int64 = 0
	AllowPinnedFolderMusicTheShortcutIsVisibleAndDisablesTheSettingInTheSettingsApp        int64 = 1
	AllowPinnedFolderMusicThereIsNoEnforcedConfigurationAndTheSettingCanBeChangedByTheUser int64 = 65535
)

// AllowPinnedFolderNetwork allowed values.
const (
	AllowPinnedFolderNetworkTheShortcutIsHiddenAndDisablesTheSettingInTheSettingsApp         int64 = 0
	AllowPinnedFolderNetworkTheShortcutIsVisibleAndDisablesTheSettingInTheSettingsApp        int64 = 1
	AllowPinnedFolderNetworkThereIsNoEnforcedConfigurationAndTheSettingCanBeChangedByTheUser int64 = 65535
)

// AllowPinnedFolderPersonalFolder allowed values.
const (
	AllowPinnedFolderPersonalFolderTheShortcutIsHiddenAndDisablesTheSettingInTheSettingsApp         int64 = 0
	AllowPinnedFolderPersonalFolderTheShortcutIsVisibleAndDisablesTheSettingInTheSettingsApp        int64 = 1
	AllowPinnedFolderPersonalFolderThereIsNoEnforcedConfigurationAndTheSettingCanBeChangedByTheUser int64 = 65535
)

// AllowPinnedFolderPictures allowed values.
const (
	AllowPinnedFolderPicturesTheShortcutIsHiddenAndDisablesTheSettingInTheSettingsApp         int64 = 0
	AllowPinnedFolderPicturesTheShortcutIsVisibleAndDisablesTheSettingInTheSettingsApp        int64 = 1
	AllowPinnedFolderPicturesThereIsNoEnforcedConfigurationAndTheSettingCanBeChangedByTheUser int64 = 65535
)

// AllowPinnedFolderSettings allowed values.
const (
	AllowPinnedFolderSettingsTheShortcutIsHiddenAndDisablesTheSettingInTheSettingsApp         int64 = 0
	AllowPinnedFolderSettingsTheShortcutIsVisibleAndDisablesTheSettingInTheSettingsApp        int64 = 1
	AllowPinnedFolderSettingsThereIsNoEnforcedConfigurationAndTheSettingCanBeChangedByTheUser int64 = 65535
)

// AllowPinnedFolderVideos allowed values.
const (
	AllowPinnedFolderVideosTheShortcutIsHiddenAndDisablesTheSettingInTheSettingsApp         int64 = 0
	AllowPinnedFolderVideosTheShortcutIsVisibleAndDisablesTheSettingInTheSettingsApp        int64 = 1
	AllowPinnedFolderVideosThereIsNoEnforcedConfigurationAndTheSettingCanBeChangedByTheUser int64 = 65535
)

// AlwaysShowNotificationIcon allowed values.
const (
	AlwaysShowNotificationIconAutoHideNotificationBellIcon int64 = 0
	AlwaysShowNotificationIconShowNotificationBellIcon     int64 = 1
)

// ConfigureTaskbarSmallButtonBehavior allowed values.
const (
	ConfigureTaskbarSmallButtonBehaviorAlwaysTheTaskbarAlwaysUsesSmallButtonsTheSettingWillBeGrayedOutInTheSettingsUIAndTheUserCanNotChangeTheSettingValue                                                                        int64 = 0
	ConfigureTaskbarSmallButtonBehaviorWhenTaskbarIsFullTheTaskbarDynamicallySwitchesBetweenSmallButtonsAndStandardSizedButtonsBasedOnAvailableSpaceTheSettingWillBeGrayedOutInTheSettingsUIAndTheUserCanNotChangeTheSettingValue int64 = 1
	ConfigureTaskbarSmallButtonBehaviorNeverTheTaskbarNeverUsesSmallButtonsOnlyStandardSizedButtonsWillBeUsedTheSettingWillBeGrayedOutInTheSettingsUIAndTheUserCanNotChangeTheSettingValue                                        int64 = 2
	ConfigureTaskbarSmallButtonBehaviorThereIsNoEnforcedConfigurationAndTheSettingCanBeChangedByTheUser                                                                                                                           int64 = 65535
)

// DisableContextMenus allowed values.
const (
	DisableContextMenusDoNotDisable int64 = 0
	DisableContextMenusDisable      int64 = 1
)

// DisableControlCenter allowed values.
const (
	DisableControlCenterEnableQuickSettings  = "0"
	DisableControlCenterDisableQuickSettings = "1"
)

// DisableEditingQuickSettings allowed values.
const (
	DisableEditingQuickSettingsEnableEditingQuickSettings  int64 = 0
	DisableEditingQuickSettingsDisableEditingQuickSettings int64 = 1
)

// ForceStartSize allowed values.
const (
	ForceStartSizeDoNotForceSizeOfStart         int64 = 0
	ForceStartSizeForceNonFullscreenSizeOfStart int64 = 1
	ForceStartSizeForceAFullscreenSizeOfStart   int64 = 2
)

// HideAppList allowed values.
const (
	HideAppListNone                                                                            int64 = 0
	HideAppListHideAllAppsList                                                                 int64 = 1
	HideAppListHideAllAppsListAndDisableShowAppListInStartMenuInSettingsApp                    int64 = 2
	HideAppListHideAllAppsListRemoveAllAppsButtonAndDisableShowAppListInStartMenuInSettingsApp int64 = 3
)

// HideCategoryView allowed values.
const (
	HideCategoryViewCategoryViewShown  int64 = 0
	HideCategoryViewCategoryViewHidden int64 = 1
)

// HideChangeAccountSettings allowed values.
const (
	HideChangeAccountSettingsDoNotHide int64 = 0
	HideChangeAccountSettingsHide      int64 = 1
)

// HideFrequentlyUsedApps allowed values.
const (
	HideFrequentlyUsedAppsDoNotHide int64 = 0
	HideFrequentlyUsedAppsHide      int64 = 1
)

// HideHibernate allowed values.
const (
	HideHibernateDoNotHide int64 = 0
	HideHibernateHide      int64 = 1
)

// HideLock allowed values.
const (
	HideLockDoNotHide int64 = 0
	HideLockHide      int64 = 1
)

// HidePeopleBar allowed values.
const (
	HidePeopleBarDoNotHide int64 = 0
	HidePeopleBarHide      int64 = 1
)

// HidePowerButton allowed values.
const (
	HidePowerButtonDoNotHide int64 = 0
	HidePowerButtonHide      int64 = 1
)

// HideRecentJumplists allowed values.
const (
	HideRecentJumplistsDoNotHide int64 = 0
	HideRecentJumplistsHide      int64 = 1
)

// HideRecentlyAddedApps allowed values.
const (
	HideRecentlyAddedAppsDoNotHide int64 = 0
	HideRecentlyAddedAppsHide      int64 = 1
)

// HideRecommendedPersonalizedSites allowed values.
const (
	HideRecommendedPersonalizedSitesPersonalizedWebsiteRecommendationsShown  int64 = 0
	HideRecommendedPersonalizedSitesPersonalizedWebsiteRecommendationsHidden int64 = 1
)

// HideRecommendedSection allowed values.
const (
	HideRecommendedSectionRecommendedSectionShown  int64 = 0
	HideRecommendedSectionRecommendedSectionHidden int64 = 1
)

// HideRestart allowed values.
const (
	HideRestartDoNotHide int64 = 0
	HideRestartHide      int64 = 1
)

// HideShutDown allowed values.
const (
	HideShutDownDoNotHide int64 = 0
	HideShutDownHide      int64 = 1
)

// HideSignOut allowed values.
const (
	HideSignOutDoNotHide int64 = 0
	HideSignOutHide      int64 = 1
)

// HideSleep allowed values.
const (
	HideSleepDoNotHide int64 = 0
	HideSleepHide      int64 = 1
)

// HideSwitchAccount allowed values.
const (
	HideSwitchAccountDoNotHide int64 = 0
	HideSwitchAccountHide      int64 = 1
)

// HideTaskViewButton allowed values.
const (
	HideTaskViewButtonTaskViewButtonShown  int64 = 0
	HideTaskViewButtonTaskViewButtonHidden int64 = 1
)

// HideUserTile allowed values.
const (
	HideUserTileDoNotHide int64 = 0
	HideUserTileHide      int64 = 1
)

// NoPinningToTaskbar allowed values.
const (
	NoPinningToTaskbarPinningEnabled  int64 = 0
	NoPinningToTaskbarPinningDisabled int64 = 1
)

// ShowOrHideMostUsedApps allowed values.
const (
	ShowOrHideMostUsedAppsDoNotEnforceVisibilityOfListOfMostUsedAppsInStartUserCanControlViaSettingsAppDefaultBehaviorEquivalentToNotConfiguringThisPolicy int64 = 0
	ShowOrHideMostUsedAppsForceShowingOfListOfMostUsedAppsInStartCorrespondingToggleInSettingAppIsDisabled                                                 int64 = 1
	ShowOrHideMostUsedAppsForceHidingOfListOfMostUsedAppsInStartCorrespondingToggleInSettingAppIsDisabled                                                  int64 = 2
)

// SimplifyQuickSettings allowed values.
const (
	SimplifyQuickSettingsLoadRegularQuickSettingsLayout    int64 = 0
	SimplifyQuickSettingsLoadSimplifiedQuickSettingsLayout int64 = 1
)

// TurnOffAbbreviatedDateTimeFormat allowed values.
const (
	TurnOffAbbreviatedDateTimeFormatShowAbbreviatedTimeAndDateFormat int64 = 0
	TurnOffAbbreviatedDateTimeFormatShowClassicTimeAndDateFormat     int64 = 1
)
