// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

//go:build windows

package policymemorydump

import (
	csp "github.com/deploymenttheory/go-bindings-wmi/runtime/csp"
	wmi "github.com/deploymenttheory/go-bindings-wmi/runtime/wmi"
)

// Service drives this CSP area's policies through the MDM bridge.
// Construct it with New, passing a wmi.Service connected to the bridge
// namespace (csp.Connect, which requires the SYSTEM account).
type Service struct{ svc *wmi.Service }

// New returns a Service bound to a connected bridge session.
func New(svc *wmi.Service) *Service { return &Service{svc: svc} }

// GetAllowCrashDump reads the effective value of AllowCrashDump.
func (s *Service) GetAllowCrashDump() (int64, error) {
	v, err := csp.Read(s.svc, AllowCrashDump)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetAllowCrashDump sets AllowCrashDump (OMA-DM Add/Replace).
func (s *Service) SetAllowCrashDump(v int64) error { return csp.Set(s.svc, AllowCrashDump, v) }

// DeleteAllowCrashDump unmanages AllowCrashDump (OMA-DM Delete).
func (s *Service) DeleteAllowCrashDump() error { return csp.Delete(s.svc, AllowCrashDump) }

// GetAllowLiveDump reads the effective value of AllowLiveDump.
func (s *Service) GetAllowLiveDump() (int64, error) {
	v, err := csp.Read(s.svc, AllowLiveDump)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetAllowLiveDump sets AllowLiveDump (OMA-DM Add/Replace).
func (s *Service) SetAllowLiveDump(v int64) error { return csp.Set(s.svc, AllowLiveDump, v) }

// DeleteAllowLiveDump unmanages AllowLiveDump (OMA-DM Delete).
func (s *Service) DeleteAllowLiveDump() error { return csp.Delete(s.svc, AllowLiveDump) }
