// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

//go:build windows

package policypower

import (
	csp "github.com/deploymenttheory/go-bindings-wmi/runtime/csp"
	wmi "github.com/deploymenttheory/go-bindings-wmi/runtime/wmi"
)

// Service drives this CSP area's policies through the MDM bridge.
// Construct it with New, passing a wmi.Service connected to the bridge
// namespace (csp.Connect, which requires the SYSTEM account).
type Service struct{ svc *wmi.Service }

// New returns a Service bound to a connected bridge session.
func New(svc *wmi.Service) *Service { return &Service{svc: svc} }

// GetAllowHibernate reads the effective value of AllowHibernate.
func (s *Service) GetAllowHibernate() (int64, error) {
	v, err := csp.Read(s.svc, AllowHibernate)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetAllowHibernate sets AllowHibernate (OMA-DM Add/Replace).
func (s *Service) SetAllowHibernate(v int64) error { return csp.Set(s.svc, AllowHibernate, v) }

// DeleteAllowHibernate unmanages AllowHibernate (OMA-DM Delete).
func (s *Service) DeleteAllowHibernate() error { return csp.Delete(s.svc, AllowHibernate) }

// GetAllowStandbyStatesWhenSleepingOnBattery reads the effective value of AllowStandbyStatesWhenSleepingOnBattery.
func (s *Service) GetAllowStandbyStatesWhenSleepingOnBattery() (string, error) {
	v, err := csp.Read(s.svc, AllowStandbyStatesWhenSleepingOnBattery)
	if err != nil {
		return "", err
	}
	return wmi.AsString(v), nil
}

// SetAllowStandbyStatesWhenSleepingOnBattery sets AllowStandbyStatesWhenSleepingOnBattery (OMA-DM Add/Replace).
func (s *Service) SetAllowStandbyStatesWhenSleepingOnBattery(v string) error {
	return csp.Set(s.svc, AllowStandbyStatesWhenSleepingOnBattery, v)
}

// DeleteAllowStandbyStatesWhenSleepingOnBattery unmanages AllowStandbyStatesWhenSleepingOnBattery (OMA-DM Delete).
func (s *Service) DeleteAllowStandbyStatesWhenSleepingOnBattery() error {
	return csp.Delete(s.svc, AllowStandbyStatesWhenSleepingOnBattery)
}

// GetAllowStandbyWhenSleepingPluggedIn reads the effective value of AllowStandbyWhenSleepingPluggedIn.
func (s *Service) GetAllowStandbyWhenSleepingPluggedIn() (string, error) {
	v, err := csp.Read(s.svc, AllowStandbyWhenSleepingPluggedIn)
	if err != nil {
		return "", err
	}
	return wmi.AsString(v), nil
}

// SetAllowStandbyWhenSleepingPluggedIn sets AllowStandbyWhenSleepingPluggedIn (OMA-DM Add/Replace).
func (s *Service) SetAllowStandbyWhenSleepingPluggedIn(v string) error {
	return csp.Set(s.svc, AllowStandbyWhenSleepingPluggedIn, v)
}

// DeleteAllowStandbyWhenSleepingPluggedIn unmanages AllowStandbyWhenSleepingPluggedIn (OMA-DM Delete).
func (s *Service) DeleteAllowStandbyWhenSleepingPluggedIn() error {
	return csp.Delete(s.svc, AllowStandbyWhenSleepingPluggedIn)
}

// GetDisplayOffTimeoutOnBattery reads the effective value of DisplayOffTimeoutOnBattery.
func (s *Service) GetDisplayOffTimeoutOnBattery() (string, error) {
	v, err := csp.Read(s.svc, DisplayOffTimeoutOnBattery)
	if err != nil {
		return "", err
	}
	return wmi.AsString(v), nil
}

// SetDisplayOffTimeoutOnBattery sets DisplayOffTimeoutOnBattery (OMA-DM Add/Replace).
func (s *Service) SetDisplayOffTimeoutOnBattery(v string) error {
	return csp.Set(s.svc, DisplayOffTimeoutOnBattery, v)
}

// DeleteDisplayOffTimeoutOnBattery unmanages DisplayOffTimeoutOnBattery (OMA-DM Delete).
func (s *Service) DeleteDisplayOffTimeoutOnBattery() error {
	return csp.Delete(s.svc, DisplayOffTimeoutOnBattery)
}

// GetDisplayOffTimeoutPluggedIn reads the effective value of DisplayOffTimeoutPluggedIn.
func (s *Service) GetDisplayOffTimeoutPluggedIn() (string, error) {
	v, err := csp.Read(s.svc, DisplayOffTimeoutPluggedIn)
	if err != nil {
		return "", err
	}
	return wmi.AsString(v), nil
}

// SetDisplayOffTimeoutPluggedIn sets DisplayOffTimeoutPluggedIn (OMA-DM Add/Replace).
func (s *Service) SetDisplayOffTimeoutPluggedIn(v string) error {
	return csp.Set(s.svc, DisplayOffTimeoutPluggedIn, v)
}

// DeleteDisplayOffTimeoutPluggedIn unmanages DisplayOffTimeoutPluggedIn (OMA-DM Delete).
func (s *Service) DeleteDisplayOffTimeoutPluggedIn() error {
	return csp.Delete(s.svc, DisplayOffTimeoutPluggedIn)
}

// GetEnableEnergySaver reads the effective value of EnableEnergySaver.
func (s *Service) GetEnableEnergySaver() (int64, error) {
	v, err := csp.Read(s.svc, EnableEnergySaver)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetEnableEnergySaver sets EnableEnergySaver (OMA-DM Add/Replace).
func (s *Service) SetEnableEnergySaver(v int64) error { return csp.Set(s.svc, EnableEnergySaver, v) }

// DeleteEnableEnergySaver unmanages EnableEnergySaver (OMA-DM Delete).
func (s *Service) DeleteEnableEnergySaver() error { return csp.Delete(s.svc, EnableEnergySaver) }

// GetEnergySaverBatteryThresholdOnBattery reads the effective value of EnergySaverBatteryThresholdOnBattery.
func (s *Service) GetEnergySaverBatteryThresholdOnBattery() (int64, error) {
	v, err := csp.Read(s.svc, EnergySaverBatteryThresholdOnBattery)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetEnergySaverBatteryThresholdOnBattery sets EnergySaverBatteryThresholdOnBattery (OMA-DM Add/Replace).
func (s *Service) SetEnergySaverBatteryThresholdOnBattery(v int64) error {
	return csp.Set(s.svc, EnergySaverBatteryThresholdOnBattery, v)
}

// DeleteEnergySaverBatteryThresholdOnBattery unmanages EnergySaverBatteryThresholdOnBattery (OMA-DM Delete).
func (s *Service) DeleteEnergySaverBatteryThresholdOnBattery() error {
	return csp.Delete(s.svc, EnergySaverBatteryThresholdOnBattery)
}

// GetEnergySaverBatteryThresholdPluggedIn reads the effective value of EnergySaverBatteryThresholdPluggedIn.
func (s *Service) GetEnergySaverBatteryThresholdPluggedIn() (int64, error) {
	v, err := csp.Read(s.svc, EnergySaverBatteryThresholdPluggedIn)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetEnergySaverBatteryThresholdPluggedIn sets EnergySaverBatteryThresholdPluggedIn (OMA-DM Add/Replace).
func (s *Service) SetEnergySaverBatteryThresholdPluggedIn(v int64) error {
	return csp.Set(s.svc, EnergySaverBatteryThresholdPluggedIn, v)
}

// DeleteEnergySaverBatteryThresholdPluggedIn unmanages EnergySaverBatteryThresholdPluggedIn (OMA-DM Delete).
func (s *Service) DeleteEnergySaverBatteryThresholdPluggedIn() error {
	return csp.Delete(s.svc, EnergySaverBatteryThresholdPluggedIn)
}

// GetHibernateTimeoutOnBattery reads the effective value of HibernateTimeoutOnBattery.
func (s *Service) GetHibernateTimeoutOnBattery() (string, error) {
	v, err := csp.Read(s.svc, HibernateTimeoutOnBattery)
	if err != nil {
		return "", err
	}
	return wmi.AsString(v), nil
}

// SetHibernateTimeoutOnBattery sets HibernateTimeoutOnBattery (OMA-DM Add/Replace).
func (s *Service) SetHibernateTimeoutOnBattery(v string) error {
	return csp.Set(s.svc, HibernateTimeoutOnBattery, v)
}

// DeleteHibernateTimeoutOnBattery unmanages HibernateTimeoutOnBattery (OMA-DM Delete).
func (s *Service) DeleteHibernateTimeoutOnBattery() error {
	return csp.Delete(s.svc, HibernateTimeoutOnBattery)
}

// GetHibernateTimeoutPluggedIn reads the effective value of HibernateTimeoutPluggedIn.
func (s *Service) GetHibernateTimeoutPluggedIn() (string, error) {
	v, err := csp.Read(s.svc, HibernateTimeoutPluggedIn)
	if err != nil {
		return "", err
	}
	return wmi.AsString(v), nil
}

// SetHibernateTimeoutPluggedIn sets HibernateTimeoutPluggedIn (OMA-DM Add/Replace).
func (s *Service) SetHibernateTimeoutPluggedIn(v string) error {
	return csp.Set(s.svc, HibernateTimeoutPluggedIn, v)
}

// DeleteHibernateTimeoutPluggedIn unmanages HibernateTimeoutPluggedIn (OMA-DM Delete).
func (s *Service) DeleteHibernateTimeoutPluggedIn() error {
	return csp.Delete(s.svc, HibernateTimeoutPluggedIn)
}

// GetRequirePasswordWhenComputerWakesOnBattery reads the effective value of RequirePasswordWhenComputerWakesOnBattery.
func (s *Service) GetRequirePasswordWhenComputerWakesOnBattery() (string, error) {
	v, err := csp.Read(s.svc, RequirePasswordWhenComputerWakesOnBattery)
	if err != nil {
		return "", err
	}
	return wmi.AsString(v), nil
}

// SetRequirePasswordWhenComputerWakesOnBattery sets RequirePasswordWhenComputerWakesOnBattery (OMA-DM Add/Replace).
func (s *Service) SetRequirePasswordWhenComputerWakesOnBattery(v string) error {
	return csp.Set(s.svc, RequirePasswordWhenComputerWakesOnBattery, v)
}

// DeleteRequirePasswordWhenComputerWakesOnBattery unmanages RequirePasswordWhenComputerWakesOnBattery (OMA-DM Delete).
func (s *Service) DeleteRequirePasswordWhenComputerWakesOnBattery() error {
	return csp.Delete(s.svc, RequirePasswordWhenComputerWakesOnBattery)
}

// GetRequirePasswordWhenComputerWakesPluggedIn reads the effective value of RequirePasswordWhenComputerWakesPluggedIn.
func (s *Service) GetRequirePasswordWhenComputerWakesPluggedIn() (string, error) {
	v, err := csp.Read(s.svc, RequirePasswordWhenComputerWakesPluggedIn)
	if err != nil {
		return "", err
	}
	return wmi.AsString(v), nil
}

// SetRequirePasswordWhenComputerWakesPluggedIn sets RequirePasswordWhenComputerWakesPluggedIn (OMA-DM Add/Replace).
func (s *Service) SetRequirePasswordWhenComputerWakesPluggedIn(v string) error {
	return csp.Set(s.svc, RequirePasswordWhenComputerWakesPluggedIn, v)
}

// DeleteRequirePasswordWhenComputerWakesPluggedIn unmanages RequirePasswordWhenComputerWakesPluggedIn (OMA-DM Delete).
func (s *Service) DeleteRequirePasswordWhenComputerWakesPluggedIn() error {
	return csp.Delete(s.svc, RequirePasswordWhenComputerWakesPluggedIn)
}

// GetSelectLidCloseActionOnBattery reads the effective value of SelectLidCloseActionOnBattery.
func (s *Service) GetSelectLidCloseActionOnBattery() (int64, error) {
	v, err := csp.Read(s.svc, SelectLidCloseActionOnBattery)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetSelectLidCloseActionOnBattery sets SelectLidCloseActionOnBattery (OMA-DM Add/Replace).
func (s *Service) SetSelectLidCloseActionOnBattery(v int64) error {
	return csp.Set(s.svc, SelectLidCloseActionOnBattery, v)
}

// DeleteSelectLidCloseActionOnBattery unmanages SelectLidCloseActionOnBattery (OMA-DM Delete).
func (s *Service) DeleteSelectLidCloseActionOnBattery() error {
	return csp.Delete(s.svc, SelectLidCloseActionOnBattery)
}

// GetSelectLidCloseActionPluggedIn reads the effective value of SelectLidCloseActionPluggedIn.
func (s *Service) GetSelectLidCloseActionPluggedIn() (int64, error) {
	v, err := csp.Read(s.svc, SelectLidCloseActionPluggedIn)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetSelectLidCloseActionPluggedIn sets SelectLidCloseActionPluggedIn (OMA-DM Add/Replace).
func (s *Service) SetSelectLidCloseActionPluggedIn(v int64) error {
	return csp.Set(s.svc, SelectLidCloseActionPluggedIn, v)
}

// DeleteSelectLidCloseActionPluggedIn unmanages SelectLidCloseActionPluggedIn (OMA-DM Delete).
func (s *Service) DeleteSelectLidCloseActionPluggedIn() error {
	return csp.Delete(s.svc, SelectLidCloseActionPluggedIn)
}

// GetSelectPowerButtonActionOnBattery reads the effective value of SelectPowerButtonActionOnBattery.
func (s *Service) GetSelectPowerButtonActionOnBattery() (int64, error) {
	v, err := csp.Read(s.svc, SelectPowerButtonActionOnBattery)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetSelectPowerButtonActionOnBattery sets SelectPowerButtonActionOnBattery (OMA-DM Add/Replace).
func (s *Service) SetSelectPowerButtonActionOnBattery(v int64) error {
	return csp.Set(s.svc, SelectPowerButtonActionOnBattery, v)
}

// DeleteSelectPowerButtonActionOnBattery unmanages SelectPowerButtonActionOnBattery (OMA-DM Delete).
func (s *Service) DeleteSelectPowerButtonActionOnBattery() error {
	return csp.Delete(s.svc, SelectPowerButtonActionOnBattery)
}

// GetSelectPowerButtonActionPluggedIn reads the effective value of SelectPowerButtonActionPluggedIn.
func (s *Service) GetSelectPowerButtonActionPluggedIn() (int64, error) {
	v, err := csp.Read(s.svc, SelectPowerButtonActionPluggedIn)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetSelectPowerButtonActionPluggedIn sets SelectPowerButtonActionPluggedIn (OMA-DM Add/Replace).
func (s *Service) SetSelectPowerButtonActionPluggedIn(v int64) error {
	return csp.Set(s.svc, SelectPowerButtonActionPluggedIn, v)
}

// DeleteSelectPowerButtonActionPluggedIn unmanages SelectPowerButtonActionPluggedIn (OMA-DM Delete).
func (s *Service) DeleteSelectPowerButtonActionPluggedIn() error {
	return csp.Delete(s.svc, SelectPowerButtonActionPluggedIn)
}

// GetSelectSleepButtonActionOnBattery reads the effective value of SelectSleepButtonActionOnBattery.
func (s *Service) GetSelectSleepButtonActionOnBattery() (int64, error) {
	v, err := csp.Read(s.svc, SelectSleepButtonActionOnBattery)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetSelectSleepButtonActionOnBattery sets SelectSleepButtonActionOnBattery (OMA-DM Add/Replace).
func (s *Service) SetSelectSleepButtonActionOnBattery(v int64) error {
	return csp.Set(s.svc, SelectSleepButtonActionOnBattery, v)
}

// DeleteSelectSleepButtonActionOnBattery unmanages SelectSleepButtonActionOnBattery (OMA-DM Delete).
func (s *Service) DeleteSelectSleepButtonActionOnBattery() error {
	return csp.Delete(s.svc, SelectSleepButtonActionOnBattery)
}

// GetSelectSleepButtonActionPluggedIn reads the effective value of SelectSleepButtonActionPluggedIn.
func (s *Service) GetSelectSleepButtonActionPluggedIn() (int64, error) {
	v, err := csp.Read(s.svc, SelectSleepButtonActionPluggedIn)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetSelectSleepButtonActionPluggedIn sets SelectSleepButtonActionPluggedIn (OMA-DM Add/Replace).
func (s *Service) SetSelectSleepButtonActionPluggedIn(v int64) error {
	return csp.Set(s.svc, SelectSleepButtonActionPluggedIn, v)
}

// DeleteSelectSleepButtonActionPluggedIn unmanages SelectSleepButtonActionPluggedIn (OMA-DM Delete).
func (s *Service) DeleteSelectSleepButtonActionPluggedIn() error {
	return csp.Delete(s.svc, SelectSleepButtonActionPluggedIn)
}

// GetStandbyTimeoutOnBattery reads the effective value of StandbyTimeoutOnBattery.
func (s *Service) GetStandbyTimeoutOnBattery() (string, error) {
	v, err := csp.Read(s.svc, StandbyTimeoutOnBattery)
	if err != nil {
		return "", err
	}
	return wmi.AsString(v), nil
}

// SetStandbyTimeoutOnBattery sets StandbyTimeoutOnBattery (OMA-DM Add/Replace).
func (s *Service) SetStandbyTimeoutOnBattery(v string) error {
	return csp.Set(s.svc, StandbyTimeoutOnBattery, v)
}

// DeleteStandbyTimeoutOnBattery unmanages StandbyTimeoutOnBattery (OMA-DM Delete).
func (s *Service) DeleteStandbyTimeoutOnBattery() error {
	return csp.Delete(s.svc, StandbyTimeoutOnBattery)
}

// GetStandbyTimeoutPluggedIn reads the effective value of StandbyTimeoutPluggedIn.
func (s *Service) GetStandbyTimeoutPluggedIn() (string, error) {
	v, err := csp.Read(s.svc, StandbyTimeoutPluggedIn)
	if err != nil {
		return "", err
	}
	return wmi.AsString(v), nil
}

// SetStandbyTimeoutPluggedIn sets StandbyTimeoutPluggedIn (OMA-DM Add/Replace).
func (s *Service) SetStandbyTimeoutPluggedIn(v string) error {
	return csp.Set(s.svc, StandbyTimeoutPluggedIn, v)
}

// DeleteStandbyTimeoutPluggedIn unmanages StandbyTimeoutPluggedIn (OMA-DM Delete).
func (s *Service) DeleteStandbyTimeoutPluggedIn() error {
	return csp.Delete(s.svc, StandbyTimeoutPluggedIn)
}

// GetTurnOffHybridSleepOnBattery reads the effective value of TurnOffHybridSleepOnBattery.
func (s *Service) GetTurnOffHybridSleepOnBattery() (int64, error) {
	v, err := csp.Read(s.svc, TurnOffHybridSleepOnBattery)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetTurnOffHybridSleepOnBattery sets TurnOffHybridSleepOnBattery (OMA-DM Add/Replace).
func (s *Service) SetTurnOffHybridSleepOnBattery(v int64) error {
	return csp.Set(s.svc, TurnOffHybridSleepOnBattery, v)
}

// DeleteTurnOffHybridSleepOnBattery unmanages TurnOffHybridSleepOnBattery (OMA-DM Delete).
func (s *Service) DeleteTurnOffHybridSleepOnBattery() error {
	return csp.Delete(s.svc, TurnOffHybridSleepOnBattery)
}

// GetTurnOffHybridSleepPluggedIn reads the effective value of TurnOffHybridSleepPluggedIn.
func (s *Service) GetTurnOffHybridSleepPluggedIn() (int64, error) {
	v, err := csp.Read(s.svc, TurnOffHybridSleepPluggedIn)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetTurnOffHybridSleepPluggedIn sets TurnOffHybridSleepPluggedIn (OMA-DM Add/Replace).
func (s *Service) SetTurnOffHybridSleepPluggedIn(v int64) error {
	return csp.Set(s.svc, TurnOffHybridSleepPluggedIn, v)
}

// DeleteTurnOffHybridSleepPluggedIn unmanages TurnOffHybridSleepPluggedIn (OMA-DM Delete).
func (s *Service) DeleteTurnOffHybridSleepPluggedIn() error {
	return csp.Delete(s.svc, TurnOffHybridSleepPluggedIn)
}

// GetUnattendedSleepTimeoutOnBattery reads the effective value of UnattendedSleepTimeoutOnBattery.
func (s *Service) GetUnattendedSleepTimeoutOnBattery() (int64, error) {
	v, err := csp.Read(s.svc, UnattendedSleepTimeoutOnBattery)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetUnattendedSleepTimeoutOnBattery sets UnattendedSleepTimeoutOnBattery (OMA-DM Add/Replace).
func (s *Service) SetUnattendedSleepTimeoutOnBattery(v int64) error {
	return csp.Set(s.svc, UnattendedSleepTimeoutOnBattery, v)
}

// DeleteUnattendedSleepTimeoutOnBattery unmanages UnattendedSleepTimeoutOnBattery (OMA-DM Delete).
func (s *Service) DeleteUnattendedSleepTimeoutOnBattery() error {
	return csp.Delete(s.svc, UnattendedSleepTimeoutOnBattery)
}

// GetUnattendedSleepTimeoutPluggedIn reads the effective value of UnattendedSleepTimeoutPluggedIn.
func (s *Service) GetUnattendedSleepTimeoutPluggedIn() (int64, error) {
	v, err := csp.Read(s.svc, UnattendedSleepTimeoutPluggedIn)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetUnattendedSleepTimeoutPluggedIn sets UnattendedSleepTimeoutPluggedIn (OMA-DM Add/Replace).
func (s *Service) SetUnattendedSleepTimeoutPluggedIn(v int64) error {
	return csp.Set(s.svc, UnattendedSleepTimeoutPluggedIn, v)
}

// DeleteUnattendedSleepTimeoutPluggedIn unmanages UnattendedSleepTimeoutPluggedIn (OMA-DM Delete).
func (s *Service) DeleteUnattendedSleepTimeoutPluggedIn() error {
	return csp.Delete(s.svc, UnattendedSleepTimeoutPluggedIn)
}
