// Command generate turns committed CIM schema snapshots (metadata/cim/*.json)
// into typed Go bindings under bindings/cim/<namespace>: one struct per class
// plus a typed query helper. Self-cleaning and byte-deterministic — running
// it twice produces no diff.
//
//	go run ./cmd/generate         # regenerate bindings/cim from metadata/cim
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/deploymenttheory/go-bindings-wmi/internal/cimschema"
)

const header = "// Code generated by go-bindings-wmi-codegen. DO NOT EDIT.\n"

func main() {
	metadataDir := "metadata/cim"
	outDir := filepath.Join("bindings", "cim")
	if len(os.Args) > 1 {
		metadataDir = os.Args[1]
	}
	if err := run(metadataDir, outDir); err != nil {
		fmt.Fprintln(os.Stderr, "generate:", err)
		os.Exit(1)
	}
}

func run(metadataDir, outDir string) error {
	entries, err := filepath.Glob(filepath.Join(metadataDir, "*.json"))
	if err != nil {
		return err
	}
	sort.Strings(entries)
	if len(entries) == 0 {
		return fmt.Errorf("no snapshots in %s (run cmd/capture)", metadataDir)
	}

	written := map[string]bool{}
	for _, entry := range entries {
		data, err := os.ReadFile(entry)
		if err != nil {
			return err
		}
		var snapshot cimschema.Snapshot
		if err := json.Unmarshal(data, &snapshot); err != nil {
			return fmt.Errorf("%s: %w", entry, err)
		}
		pkg := packageName(snapshot.Namespace)
		pkgDir := filepath.Join(outDir, pkg)
		if err := os.MkdirAll(pkgDir, 0o755); err != nil {
			return err
		}
		source, err := renderPackage(pkg, &snapshot)
		if err != nil {
			return fmt.Errorf("%s: %w", entry, err)
		}
		path := filepath.Join(pkgDir, pkg+"_classes.go")
		if err := os.WriteFile(path, source, 0o644); err != nil {
			return err
		}
		written[path] = true
		fmt.Printf("generated %d classes → %s\n", len(snapshot.Classes), path)
	}
	return pruneStale(outDir, written)
}

// packageName derives a Go package name from a CIM namespace
// (root\cimv2 → cimv2).
func packageName(namespace string) string {
	parts := strings.Split(namespace, `\`)
	return strings.ToLower(parts[len(parts)-1])
}

func renderPackage(pkg string, snapshot *cimschema.Snapshot) ([]byte, error) {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("\n//go:build windows\n\n")
	fmt.Fprintf(&b, "// Package %s binds the %s CIM classes.\n", pkg, snapshot.Namespace)
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("import wmi \"github.com/deploymenttheory/go-bindings-wmi/runtime/wmi\"\n\n")

	for _, class := range snapshot.Classes {
		goName := exportName(class.Name)
		fmt.Fprintf(&b, "// %s is the %s CIM class.\n", goName, class.Name)
		fmt.Fprintf(&b, "type %s struct {\n", goName)
		for _, p := range class.Properties {
			fmt.Fprintf(&b, "\t%s %s `cim:%q`\n", exportName(p.Name), cimschema.GoType(p), p.Name)
		}
		b.WriteString("}\n\n")

		// Typed query helper: run WQL and unmarshal rows into []T.
		fmt.Fprintf(&b, "// Query%s runs the WQL query against the class and decodes each\n", goName)
		fmt.Fprintf(&b, "// instance into a %s. Pass the WHERE clause (or \"\" for all).\n", goName)
		fmt.Fprintf(&b, "func Query%s(svc *wmi.Service, where string) ([]%s, error) {\n", goName, goName)
		fmt.Fprintf(&b, "\tq := \"SELECT * FROM %s\"\n", class.Name)
		b.WriteString("\tif where != \"\" {\n\t\tq += \" WHERE \" + where\n\t}\n")
		b.WriteString("\trows, err := svc.Query(q)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n")
		fmt.Fprintf(&b, "\tout := make([]%s, len(rows))\n", goName)
		b.WriteString("\tfor i, row := range rows {\n")
		for _, p := range class.Properties {
			field := exportName(p.Name)
			fmt.Fprintf(&b, "\t\tif v, ok := row[%q].(%s); ok {\n\t\t\tout[i].%s = v\n\t\t}\n",
				p.Name, cimschema.GoType(p), field)
		}
		b.WriteString("\t}\n\treturn out, nil\n}\n\n")
	}

	return format.Source([]byte(b.String()))
}

// exportName upper-cases the first letter and strips characters Go rejects in
// identifiers (CIM names are already CamelCase ASCII).
func exportName(name string) string {
	var out []rune
	upperNext := true
	for _, r := range name {
		if r == '_' {
			upperNext = true
			continue
		}
		if upperNext && r >= 'a' && r <= 'z' {
			r = r - 'a' + 'A'
		}
		upperNext = false
		out = append(out, r)
	}
	return string(out)
}

// pruneStale removes generated files this run did not write.
func pruneStale(outDir string, written map[string]bool) error {
	if _, err := os.Stat(outDir); err != nil {
		return nil
	}
	return filepath.WalkDir(outDir, func(path string, entry os.DirEntry, err error) error {
		if err != nil || entry.IsDir() || !strings.HasSuffix(path, ".go") || written[path] {
			return err
		}
		content, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		if bytes.HasPrefix(content, []byte(header)) {
			return os.Remove(path)
		}
		return nil
	})
}
