// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

package policyadmxkdc

import csp "github.com/deploymenttheory/go-bindings-wmi/runtime/csp"

var CbacAndArmor = csp.Policy{
	Name:       "CbacAndArmor",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_kdc/CbacAndArmor",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "kdc~AT~System~KDC", Name: "CbacAndArmor", File: "kdc.admx"}},
}

var ForestSearch = csp.Policy{
	Name:       "ForestSearch",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_kdc/ForestSearch",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "kdc~AT~System~KDC", Name: "ForestSearch", File: "kdc.admx"}},
}

var PKINITFreshness = csp.Policy{
	Name:       "PKINITFreshness",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_kdc/PKINITFreshness",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "kdc~AT~System~KDC", Name: "PKINITFreshness", File: "kdc.admx"}},
}

var RequestCompoundId = csp.Policy{
	Name:       "RequestCompoundId",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_kdc/RequestCompoundId",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "kdc~AT~System~KDC", Name: "RequestCompoundId", File: "kdc.admx"}},
}

var TicketSizeThreshold = csp.Policy{
	Name:       "TicketSizeThreshold",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_kdc/TicketSizeThreshold",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "kdc~AT~System~KDC", Name: "TicketSizeThreshold", File: "kdc.admx"}},
}

var Emitlili = csp.Policy{
	Name:       "emitlili",
	URI:        "./Device/Vendor/MSFT/Policy/Config/ADMX_kdc/emitlili",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000, 10.0.19043.1202, 10.0.19042.1202, 10.0.19041.1202",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ADMX", ADMX: &csp.ADMXBacking{Area: "kdc~AT~System~KDC", Name: "emitlili", File: "kdc.admx"}},
}

// All lists every policy in this CSP area.
var All = []csp.Policy{
	CbacAndArmor,
	ForestSearch,
	PKINITFreshness,
	RequestCompoundId,
	TicketSizeThreshold,
	Emitlili,
}
