// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

package policygames

import csp "github.com/deploymenttheory/go-bindings-wmi/runtime/csp"

// AllowAdvancedGamingServices: Specifies whether advanced gaming services can be used. These services may send data to Microsoft or publishers of games that use these services.
var AllowAdvancedGamingServices = csp.Policy{
	Name:       "AllowAdvancedGamingServices",
	URI:        "./Device/Vendor/MSFT/Policy/Config/Games/AllowAdvancedGamingServices",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "1",
	MinOSBuild: "10.0.15063",
	CSPVersion: "5.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "0", Description: "Not allowed."}, {Value: "1", Description: "Allowed."}}},
	Bridge:     &csp.Bridge{ConfigClass: "MDM_Policy_Config01_Games02", ResultClass: "MDM_Policy_Result01_Games02", InstanceID: "Games", ParentID: "./Vendor/MSFT/Policy/Config", Property: "AllowAdvancedGamingServices"},
}

// DisableGamingFullScreenExperience: Specifies whether the gaming full screen experience can be used.
var DisableGamingFullScreenExperience = csp.Policy{
	Name:       "DisableGamingFullScreenExperience",
	URI:        "./Device/Vendor/MSFT/Policy/Config/Games/DisableGamingFullScreenExperience",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "0",
	MinOSBuild: "99.9.99999",
	CSPVersion: "9.9",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "0", Description: "Gaming full screen experience allowed."}, {Value: "1", Description: "Gaming full screen experience disabled."}}},
	Bridge:     &csp.Bridge{ConfigClass: "MDM_Policy_Config01_Games02", ResultClass: "MDM_Policy_Result01_Games02", InstanceID: "Games", ParentID: "./Vendor/MSFT/Policy/Config", Property: "DisableGamingFullScreenExperience"},
}

// All lists every policy in this CSP area.
var All = []csp.Policy{
	AllowAdvancedGamingServices,
	DisableGamingFullScreenExperience,
}
