// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

package firewall

// MdmStoreDomainProfileDefaultInboundAction allowed values.
const (
	MdmStoreDomainProfileDefaultInboundActionAllowInboundByDefault int64 = 0
	MdmStoreDomainProfileDefaultInboundActionBlockInboundByDefault int64 = 1
)

// MdmStoreDomainProfileDefaultOutboundAction allowed values.
const (
	MdmStoreDomainProfileDefaultOutboundActionAllowOutboundByDefault int64 = 0
	MdmStoreDomainProfileDefaultOutboundActionBlockOutboundByDefault int64 = 1
)

// MdmStoreFirewallRulesActionType allowed values.
const (
	MdmStoreFirewallRulesActionTypeBlock int64 = 0
	MdmStoreFirewallRulesActionTypeAllow int64 = 1
)

// MdmStoreFirewallRulesDirection allowed values.
const (
	MdmStoreFirewallRulesDirectionTheRuleAppliesToInboundTraffic  = "IN"
	MdmStoreFirewallRulesDirectionTheRuleAppliesToOutboundTraffic = "OUT"
)

// MdmStoreFirewallRulesInterfaceTypes allowed values.
const (
	MdmStoreFirewallRulesInterfaceTypesRemoteAccess    = "RemoteAccess"
	MdmStoreFirewallRulesInterfaceTypesWireless        = "Wireless"
	MdmStoreFirewallRulesInterfaceTypesLan             = "Lan"
	MdmStoreFirewallRulesInterfaceTypesMobileBroadband = "MBB"
	MdmStoreFirewallRulesInterfaceTypesAll             = "All"
)

// MdmStoreFirewallRulesProfiles allowed values.
const (
	MdmStoreFirewallRulesProfilesFWPROFILETYPEDOMAINThisValueRepresentsTheProfileForNetworksThatAreConnectedToDomains                                                                                                                                                                                                                                                                                                                                                                                                         int64 = 1
	MdmStoreFirewallRulesProfilesFWPROFILETYPESTANDARDThisValueRepresentsTheStandardProfileForNetworksTheseNetworksAreClassifiedAsPrivateByTheAdministratorsInTheServerHostTheClassificationHappensTheFirstTimeTheHostConnectsToTheNetworkUsuallyTheseNetworksAreBehindNetworkAddressTranslationNATDevicesRoutersAndOtherEdgeDevicesAndTheyAreInAPrivateLocationSuchAsAHomeOrAnOfficeANDFWPROFILETYPEPRIVATEThisValueRepresentsTheProfileForPrivateNetworksWhichIsRepresentedByTheSameValueAsThatUsedForFWPROFILETYPESTANDARD int64 = 2
	MdmStoreFirewallRulesProfilesFWPROFILETYPEPUBLICThisValueRepresentsTheProfileForPublicNetworksTheseNetworksAreClassifiedAsPublicByTheAdministratorsInTheServerHostTheClassificationHappensTheFirstTimeTheHostConnectsToTheNetworkUsuallyTheseNetworksAreThoseAtAirportsCoffeeShopsAndOtherPublicPlacesWhereThePeersInTheNetworkOrTheNetworkAdministratorAreNotTrusted                                                                                                                                                     int64 = 4
	MdmStoreFirewallRulesProfilesFWPROFILETYPEALLThisValueRepresentsAllTheseNetworkSetsAndAnyFutureNetworkSets                                                                                                                                                                                                                                                                                                                                                                                                                int64 = 2147483647
	MdmStoreFirewallRulesProfilesFWPROFILETYPECURRENTThisValueRepresentsTheCurrentProfilesToWhichTheFirewallAndAdvancedSecurityComponentsDetermineTheHostIsConnectedAtTheMomentOfTheCallThisValueCanBeSpecifiedOnlyInMethodCallsAndItCannotBeCombinedWithOtherFlags                                                                                                                                                                                                                                                           int64 = 2147483648
)

// MdmStoreGlobalCRLcheck allowed values.
const (
	MdmStoreGlobalCRLcheckDisablesCRLChecking                                                                                                                                                                                                          int64 = 0
	MdmStoreGlobalCRLcheckSpecifiesThatCRLCheckingIsAttemptedAndThatCertificateValidationFailsOnlyIfTheCertificateIsRevokedOtherFailuresThatAreEncounteredDuringCRLCheckingSuchAsTheRevocationURLBeingUnreachableDoNotCauseCertificateValidationToFail int64 = 1
	MdmStoreGlobalCRLcheckMeansThatCheckingIsRequiredAndThatCertificateValidationFailsIfAnyErrorIsEncounteredDuringCRLProcessing                                                                                                                       int64 = 2
)

// MdmStoreGlobalEnablePacketQueue allowed values.
const (
	MdmStoreGlobalEnablePacketQueueIndicatesThatAllQueuingIsToBeDisabled                                    int64 = 0
	MdmStoreGlobalEnablePacketQueueSpecifiesThatInboundEncryptedPacketsAreToBeQueued                        int64 = 1
	MdmStoreGlobalEnablePacketQueueSpecifiesThatPacketsAreToBeQueuedAfterDecryptionIsPerformedForForwarding int64 = 2
)

// MdmStoreGlobalIPsecExempt allowed values.
const (
	MdmStoreGlobalIPsecExemptFWGLOBALCONFIGIPSECEXEMPTNONENoIPsecExemptions                                        int64 = 0
	MdmStoreGlobalIPsecExemptFWGLOBALCONFIGIPSECEXEMPTNEIGHBORDISCExemptNeighborDiscoverIPv6ICMPTypeCodesFromIPsec int64 = 1
	MdmStoreGlobalIPsecExemptFWGLOBALCONFIGIPSECEXEMPTICMPExemptICMPFromIPsec                                      int64 = 2
	MdmStoreGlobalIPsecExemptFWGLOBALCONFIGIPSECEXEMPTROUTERDISCExemptRouterDiscoverIPv6ICMPTypeCodesFromIPsec     int64 = 4
	MdmStoreGlobalIPsecExemptFWGLOBALCONFIGIPSECEXEMPTDHCPExemptBothIPv4AndIPv6DHCPTrafficFromIPsec                int64 = 8
)

// MdmStoreGlobalPresharedKeyEncoding allowed values.
const (
	MdmStoreGlobalPresharedKeyEncodingFWGLOBALCONFIGPRESHAREDKEYENCODINGNONEPresharedKeyIsNotEncodedInsteadItIsKeptInItsWideCharacterFormatThisSymbolicConstantHasAValueOf0 int64 = 0
	MdmStoreGlobalPresharedKeyEncodingFWGLOBALCONFIGPRESHAREDKEYENCODINGUTF8EncodeThePresharedKeyUsingUTF8ThisSymbolicConstantHasAValueOf1                                  int64 = 1
)

// MdmStoreHyperVFirewallRulesAction allowed values.
const (
	MdmStoreHyperVFirewallRulesActionBlock int64 = 0
	MdmStoreHyperVFirewallRulesActionAllow int64 = 1
)

// MdmStoreHyperVFirewallRulesDirection allowed values.
const (
	MdmStoreHyperVFirewallRulesDirectionTheRuleAppliesToInboundTraffic  = "IN"
	MdmStoreHyperVFirewallRulesDirectionTheRuleAppliesToOutboundTraffic = "OUT"
)

// MdmStoreHyperVFirewallRulesProfiles allowed values.
const (
	MdmStoreHyperVFirewallRulesProfilesFWPROFILETYPEDOMAINThisValueRepresentsTheProfileForNetworksThatAreConnectedToDomains                                                                                                                                                                                                                                                                                                                                                                                                         int64 = 1
	MdmStoreHyperVFirewallRulesProfilesFWPROFILETYPESTANDARDThisValueRepresentsTheStandardProfileForNetworksTheseNetworksAreClassifiedAsPrivateByTheAdministratorsInTheServerHostTheClassificationHappensTheFirstTimeTheHostConnectsToTheNetworkUsuallyTheseNetworksAreBehindNetworkAddressTranslationNATDevicesRoutersAndOtherEdgeDevicesAndTheyAreInAPrivateLocationSuchAsAHomeOrAnOfficeANDFWPROFILETYPEPRIVATEThisValueRepresentsTheProfileForPrivateNetworksWhichIsRepresentedByTheSameValueAsThatUsedForFWPROFILETYPESTANDARD int64 = 2
	MdmStoreHyperVFirewallRulesProfilesFWPROFILETYPEPUBLICThisValueRepresentsTheProfileForPublicNetworksTheseNetworksAreClassifiedAsPublicByTheAdministratorsInTheServerHostTheClassificationHappensTheFirstTimeTheHostConnectsToTheNetworkUsuallyTheseNetworksAreThoseAtAirportsCoffeeShopsAndOtherPublicPlacesWhereThePeersInTheNetworkOrTheNetworkAdministratorAreNotTrusted                                                                                                                                                     int64 = 4
	MdmStoreHyperVFirewallRulesProfilesFWPROFILETYPEALLThisValueRepresentsAllTheseNetworkSetsAndAnyFutureNetworkSets                                                                                                                                                                                                                                                                                                                                                                                                                int64 = 2147483647
)

// MdmStoreHyperVVMSettingsDefaultInboundAction allowed values.
const (
	MdmStoreHyperVVMSettingsDefaultInboundActionAllowInboundByDefault int64 = 0
	MdmStoreHyperVVMSettingsDefaultInboundActionBlockInboundByDefault int64 = 1
)

// MdmStoreHyperVVMSettingsDefaultOutboundAction allowed values.
const (
	MdmStoreHyperVVMSettingsDefaultOutboundActionAllowOutboundByDefault int64 = 0
	MdmStoreHyperVVMSettingsDefaultOutboundActionBlockOutboundByDefault int64 = 1
)

// MdmStoreHyperVVMSettingsDomainProfileDefaultInboundAction allowed values.
const (
	MdmStoreHyperVVMSettingsDomainProfileDefaultInboundActionAllowInboundByDefault int64 = 0
	MdmStoreHyperVVMSettingsDomainProfileDefaultInboundActionBlockInboundByDefault int64 = 1
)

// MdmStoreHyperVVMSettingsDomainProfileDefaultOutboundAction allowed values.
const (
	MdmStoreHyperVVMSettingsDomainProfileDefaultOutboundActionAllowOutboundByDefault int64 = 0
	MdmStoreHyperVVMSettingsDomainProfileDefaultOutboundActionBlockOutboundByDefault int64 = 1
)

// MdmStoreHyperVVMSettingsPrivateProfileDefaultInboundAction allowed values.
const (
	MdmStoreHyperVVMSettingsPrivateProfileDefaultInboundActionAllowInboundByDefault int64 = 0
	MdmStoreHyperVVMSettingsPrivateProfileDefaultInboundActionBlockInboundByDefault int64 = 1
)

// MdmStoreHyperVVMSettingsPrivateProfileDefaultOutboundAction allowed values.
const (
	MdmStoreHyperVVMSettingsPrivateProfileDefaultOutboundActionAllowOutboundByDefault int64 = 0
	MdmStoreHyperVVMSettingsPrivateProfileDefaultOutboundActionBlockOutboundByDefault int64 = 1
)

// MdmStoreHyperVVMSettingsPublicProfileDefaultInboundAction allowed values.
const (
	MdmStoreHyperVVMSettingsPublicProfileDefaultInboundActionAllowInboundByDefault int64 = 0
	MdmStoreHyperVVMSettingsPublicProfileDefaultInboundActionBlockInboundByDefault int64 = 1
)

// MdmStoreHyperVVMSettingsPublicProfileDefaultOutboundAction allowed values.
const (
	MdmStoreHyperVVMSettingsPublicProfileDefaultOutboundActionAllowOutboundByDefault int64 = 0
	MdmStoreHyperVVMSettingsPublicProfileDefaultOutboundActionBlockOutboundByDefault int64 = 1
)

// MdmStorePrivateProfileDefaultInboundAction allowed values.
const (
	MdmStorePrivateProfileDefaultInboundActionAllowInboundByDefault int64 = 0
	MdmStorePrivateProfileDefaultInboundActionBlockInboundByDefault int64 = 1
)

// MdmStorePrivateProfileDefaultOutboundAction allowed values.
const (
	MdmStorePrivateProfileDefaultOutboundActionAllowOutboundByDefault int64 = 0
	MdmStorePrivateProfileDefaultOutboundActionBlockOutboundByDefault int64 = 1
)

// MdmStorePublicProfileDefaultInboundAction allowed values.
const (
	MdmStorePublicProfileDefaultInboundActionAllowInboundByDefault int64 = 0
	MdmStorePublicProfileDefaultInboundActionBlockInboundByDefault int64 = 1
)

// MdmStorePublicProfileDefaultOutboundAction allowed values.
const (
	MdmStorePublicProfileDefaultOutboundActionAllowOutboundByDefault int64 = 0
	MdmStorePublicProfileDefaultOutboundActionBlockOutboundByDefault int64 = 1
)
