// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

package policyconnectivity

// AllowBluetooth allowed values.
const (
	AllowBluetoothDisallowBluetoothIfThisIsSetTo0TheRadioInTheBluetoothControlPanelWillBeGrayedOutAndTheUserWillNotBeAbleToTurnBluetoothOn int64 = 0
	AllowBluetoothAllowBluetoothIfThisIsSetTo2TheRadioInTheBluetoothControlPanelWillBeFunctionalAndTheUserWillBeAbleToTurnBluetoothOn      int64 = 2
)

// AllowCellularData allowed values.
const (
	AllowCellularDataDoNotAllowTheCellularDataChannelTheUserCannotTurnItOnThisValueIsNotSupportedInWindows10Version1511 int64 = 0
	AllowCellularDataAllowTheCellularDataChannelTheUserCanTurnItOff                                                     int64 = 1
	AllowCellularDataAllowTheCellularDataChannelTheUserCannotTurnItOff                                                  int64 = 2
)

// AllowCellularDataRoaming allowed values.
const (
	AllowCellularDataRoamingDoNotAllowCellularDataRoamingTheUserCannotTurnItOnThisValueIsNotSupportedInWindows10Version1511 int64 = 0
	AllowCellularDataRoamingAllowCellularDataRoaming                                                                        int64 = 1
	AllowCellularDataRoamingAllowCellularDataRoamingOnTheUserCannotTurnItOff                                                int64 = 2
)

// AllowConnectedDevices allowed values.
const (
	AllowConnectedDevicesDisableCDPServiceNotAvailable int64 = 0
	AllowConnectedDevicesAllowCDPServiceAvailable      int64 = 1
)

// AllowNFC allowed values.
const (
	AllowNFCDisabled int64 = 0
	AllowNFCEnabled  int64 = 1
)

// AllowPhonePCLinking allowed values.
const (
	AllowPhonePCLinkingDoNotLink           int64 = 0
	AllowPhonePCLinkingAllowPhonePCLinking int64 = 1
)

// AllowUSBConnection allowed values.
const (
	AllowUSBConnectionNotAllowed int64 = 0
	AllowUSBConnectionAllowed    int64 = 1
)

// AllowVPNOverCellular allowed values.
const (
	AllowVPNOverCellularVPNIsNotAllowedOverCellular             int64 = 0
	AllowVPNOverCellularVPNCanUseAnyConnectionIncludingCellular int64 = 1
)

// AllowVPNRoamingOverCellular allowed values.
const (
	AllowVPNRoamingOverCellularNotAllowed int64 = 0
	AllowVPNRoamingOverCellularAllowed    int64 = 1
)

// DisableCellularOperatorSettingsPage allowed values.
const (
	DisableCellularOperatorSettingsPageDisabled int64 = 0
	DisableCellularOperatorSettingsPageEnabled  int64 = 1
)

// DisableCellularSettingsPage allowed values.
const (
	DisableCellularSettingsPageDisabled int64 = 0
	DisableCellularSettingsPageEnabled  int64 = 1
)

// DisableCrossDeviceResume allowed values.
const (
	DisableCrossDeviceResumeCrossDeviceResumeIsEnabled  int64 = 0
	DisableCrossDeviceResumeCrossDeviceResumeIsDisabled int64 = 1
)

// DisallowNetworkConnectivityActiveTests allowed values.
const (
	DisallowNetworkConnectivityActiveTestsAllow int64 = 1
	DisallowNetworkConnectivityActiveTestsBlock int64 = 0
)

// UseCellularWhenWiFiPoor allowed values.
const (
	UseCellularWhenWiFiPoorDisabled int64 = 0
	UseCellularWhenWiFiPoorEnabled  int64 = 1
)
