// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

//go:build windows

package reboot

import (
	csp "github.com/deploymenttheory/go-bindings-wmi/runtime/csp"
	wmi "github.com/deploymenttheory/go-bindings-wmi/runtime/wmi"
)

// Service drives this CSP area's policies through the MDM bridge.
// Construct it with New, passing a wmi.Service connected to the bridge
// namespace (csp.Connect, which requires the SYSTEM account).
type Service struct{ svc *wmi.Service }

// New returns a Service bound to a connected bridge session.
func New(svc *wmi.Service) *Service { return &Service{svc: svc} }

// GetScheduleDailyRecurrent reads the effective value of DailyRecurrent.
func (s *Service) GetScheduleDailyRecurrent() (string, error) {
	v, err := csp.Read(s.svc, ScheduleDailyRecurrent)
	if err != nil {
		return "", err
	}
	return wmi.AsString(v), nil
}

// SetScheduleDailyRecurrent sets DailyRecurrent (OMA-DM Add/Replace).
func (s *Service) SetScheduleDailyRecurrent(v string) error {
	return csp.Set(s.svc, ScheduleDailyRecurrent, v)
}

// DeleteScheduleDailyRecurrent unmanages DailyRecurrent (OMA-DM Delete).
func (s *Service) DeleteScheduleDailyRecurrent() error {
	return csp.Delete(s.svc, ScheduleDailyRecurrent)
}

// GetScheduleSingle reads the effective value of Single.
func (s *Service) GetScheduleSingle() (string, error) {
	v, err := csp.Read(s.svc, ScheduleSingle)
	if err != nil {
		return "", err
	}
	return wmi.AsString(v), nil
}

// SetScheduleSingle sets Single (OMA-DM Add/Replace).
func (s *Service) SetScheduleSingle(v string) error { return csp.Set(s.svc, ScheduleSingle, v) }

// DeleteScheduleSingle unmanages Single (OMA-DM Delete).
func (s *Service) DeleteScheduleSingle() error { return csp.Delete(s.svc, ScheduleSingle) }
