// Code generated by go-bindings-wmi-codegen. DO NOT EDIT.

//go:build windows

package securitycenter2

import wmi "github.com/deploymenttheory/go-bindings-wmi/runtime/wmi"

// SystemSecurityGet9XUserListResult holds the out-parameters of __SystemSecurity.Get9XUserList.
type SystemSecurityGet9XUserListResult struct {
	Ul          []wmi.Row
	ReturnValue uint32
}

// Err returns nil when ReturnValue is 0, else a *wmi.JobError carrying
// the code.
func (r *SystemSecurityGet9XUserListResult) Err() error {
	if r.ReturnValue == 0 {
		return nil
	}
	return &wmi.JobError{What: "__SystemSecurity.Get9XUserList", ReturnValue: uint32(r.ReturnValue)}
}

// SystemSecurityGet9XUserList invokes the static __SystemSecurity.Get9XUserList method. Nil in-parameters
// are omitted so the provider applies its defaults; non-nil values are
// always sent, including zeros (build them inline with wmi.Ptr).
func SystemSecurityGet9XUserList(svc *wmi.Service) (*SystemSecurityGet9XUserListResult, error) {
	row, err := svc.ExecMethod("__SystemSecurity", "Get9XUserList", nil)
	if err != nil {
		return nil, err
	}
	out := &SystemSecurityGet9XUserListResult{}
	out.Ul = wmi.AsRowSlice(row["ul"])
	out.ReturnValue = wmi.AsUint32(row["ReturnValue"])
	return out, nil
}

// SystemSecurityGetCallerAccessRightsResult holds the out-parameters of __SystemSecurity.GetCallerAccessRights.
type SystemSecurityGetCallerAccessRightsResult struct {
	Rights      int32
	ReturnValue uint32
}

// Err returns nil when ReturnValue is 0, else a *wmi.JobError carrying
// the code.
func (r *SystemSecurityGetCallerAccessRightsResult) Err() error {
	if r.ReturnValue == 0 {
		return nil
	}
	return &wmi.JobError{What: "__SystemSecurity.GetCallerAccessRights", ReturnValue: uint32(r.ReturnValue)}
}

// SystemSecurityGetCallerAccessRights invokes the static __SystemSecurity.GetCallerAccessRights method. Nil in-parameters
// are omitted so the provider applies its defaults; non-nil values are
// always sent, including zeros (build them inline with wmi.Ptr).
func SystemSecurityGetCallerAccessRights(svc *wmi.Service) (*SystemSecurityGetCallerAccessRightsResult, error) {
	row, err := svc.ExecMethod("__SystemSecurity", "GetCallerAccessRights", nil)
	if err != nil {
		return nil, err
	}
	out := &SystemSecurityGetCallerAccessRightsResult{}
	out.Rights = wmi.AsInt32(row["rights"])
	out.ReturnValue = wmi.AsUint32(row["ReturnValue"])
	return out, nil
}

// SystemSecurityGetSDResult holds the out-parameters of __SystemSecurity.GetSD.
type SystemSecurityGetSDResult struct {
	SD          []uint8
	ReturnValue uint32
}

// Err returns nil when ReturnValue is 0, else a *wmi.JobError carrying
// the code.
func (r *SystemSecurityGetSDResult) Err() error {
	if r.ReturnValue == 0 {
		return nil
	}
	return &wmi.JobError{What: "__SystemSecurity.GetSD", ReturnValue: uint32(r.ReturnValue)}
}

// SystemSecurityGetSD invokes the static __SystemSecurity.GetSD method. Nil in-parameters
// are omitted so the provider applies its defaults; non-nil values are
// always sent, including zeros (build them inline with wmi.Ptr).
func SystemSecurityGetSD(svc *wmi.Service) (*SystemSecurityGetSDResult, error) {
	row, err := svc.ExecMethod("__SystemSecurity", "GetSD", nil)
	if err != nil {
		return nil, err
	}
	out := &SystemSecurityGetSDResult{}
	out.SD = wmi.AsUint8Slice(row["SD"])
	out.ReturnValue = wmi.AsUint32(row["ReturnValue"])
	return out, nil
}

// SystemSecurityGetSecurityDescriptorResult holds the out-parameters of __SystemSecurity.GetSecurityDescriptor.
type SystemSecurityGetSecurityDescriptorResult struct {
	Descriptor  wmi.Row
	ReturnValue uint32
}

// Err returns nil when ReturnValue is 0, else a *wmi.JobError carrying
// the code.
func (r *SystemSecurityGetSecurityDescriptorResult) Err() error {
	if r.ReturnValue == 0 {
		return nil
	}
	return &wmi.JobError{What: "__SystemSecurity.GetSecurityDescriptor", ReturnValue: uint32(r.ReturnValue)}
}

// SystemSecurityGetSecurityDescriptor invokes the static __SystemSecurity.GetSecurityDescriptor method. Nil in-parameters
// are omitted so the provider applies its defaults; non-nil values are
// always sent, including zeros (build them inline with wmi.Ptr).
func SystemSecurityGetSecurityDescriptor(svc *wmi.Service) (*SystemSecurityGetSecurityDescriptorResult, error) {
	row, err := svc.ExecMethod("__SystemSecurity", "GetSecurityDescriptor", nil)
	if err != nil {
		return nil, err
	}
	out := &SystemSecurityGetSecurityDescriptorResult{}
	if v, ok := row["Descriptor"].(wmi.Row); ok {
		out.Descriptor = v
	}
	out.ReturnValue = wmi.AsUint32(row["ReturnValue"])
	return out, nil
}

// SystemSecuritySet9XUserListResult holds the out-parameters of __SystemSecurity.Set9XUserList.
type SystemSecuritySet9XUserListResult struct {
	ReturnValue uint32
}

// Err returns nil when ReturnValue is 0, else a *wmi.JobError carrying
// the code.
func (r *SystemSecuritySet9XUserListResult) Err() error {
	if r.ReturnValue == 0 {
		return nil
	}
	return &wmi.JobError{What: "__SystemSecurity.Set9XUserList", ReturnValue: uint32(r.ReturnValue)}
}

// SystemSecuritySet9XUserList invokes the static __SystemSecurity.Set9XUserList method. Nil in-parameters
// are omitted so the provider applies its defaults; non-nil values are
// always sent, including zeros (build them inline with wmi.Ptr).
func SystemSecuritySet9XUserList(svc *wmi.Service, ul []wmi.Row) (*SystemSecuritySet9XUserListResult, error) {
	in := map[string]any{}
	if ul != nil {
		in["ul"] = ul
	}
	row, err := svc.ExecMethod("__SystemSecurity", "Set9XUserList", in)
	if err != nil {
		return nil, err
	}
	out := &SystemSecuritySet9XUserListResult{}
	out.ReturnValue = wmi.AsUint32(row["ReturnValue"])
	return out, nil
}

// SystemSecuritySetSDResult holds the out-parameters of __SystemSecurity.SetSD.
type SystemSecuritySetSDResult struct {
	ReturnValue uint32
}

// Err returns nil when ReturnValue is 0, else a *wmi.JobError carrying
// the code.
func (r *SystemSecuritySetSDResult) Err() error {
	if r.ReturnValue == 0 {
		return nil
	}
	return &wmi.JobError{What: "__SystemSecurity.SetSD", ReturnValue: uint32(r.ReturnValue)}
}

// SystemSecuritySetSD invokes the static __SystemSecurity.SetSD method. Nil in-parameters
// are omitted so the provider applies its defaults; non-nil values are
// always sent, including zeros (build them inline with wmi.Ptr).
func SystemSecuritySetSD(svc *wmi.Service, sD []uint8) (*SystemSecuritySetSDResult, error) {
	in := map[string]any{}
	if sD != nil {
		in["SD"] = sD
	}
	row, err := svc.ExecMethod("__SystemSecurity", "SetSD", in)
	if err != nil {
		return nil, err
	}
	out := &SystemSecuritySetSDResult{}
	out.ReturnValue = wmi.AsUint32(row["ReturnValue"])
	return out, nil
}

// SystemSecuritySetSecurityDescriptorResult holds the out-parameters of __SystemSecurity.SetSecurityDescriptor.
type SystemSecuritySetSecurityDescriptorResult struct {
	ReturnValue uint32
}

// Err returns nil when ReturnValue is 0, else a *wmi.JobError carrying
// the code.
func (r *SystemSecuritySetSecurityDescriptorResult) Err() error {
	if r.ReturnValue == 0 {
		return nil
	}
	return &wmi.JobError{What: "__SystemSecurity.SetSecurityDescriptor", ReturnValue: uint32(r.ReturnValue)}
}

// SystemSecuritySetSecurityDescriptor invokes the static __SystemSecurity.SetSecurityDescriptor method. Nil in-parameters
// are omitted so the provider applies its defaults; non-nil values are
// always sent, including zeros (build them inline with wmi.Ptr).
func SystemSecuritySetSecurityDescriptor(svc *wmi.Service, descriptor wmi.Row) (*SystemSecuritySetSecurityDescriptorResult, error) {
	in := map[string]any{}
	if descriptor != nil {
		in["Descriptor"] = descriptor
	}
	row, err := svc.ExecMethod("__SystemSecurity", "SetSecurityDescriptor", in)
	if err != nil {
		return nil, err
	}
	out := &SystemSecuritySetSecurityDescriptorResult{}
	out.ReturnValue = wmi.AsUint32(row["ReturnValue"])
	return out, nil
}
