// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

package declaredconfiguration

// HostCompleteDocumentsPropertiesAbandoned allowed values.
const (
	HostCompleteDocumentsPropertiesAbandonedTheDocumentIsNoLongerManaged int64 = 0
	HostCompleteDocumentsPropertiesAbandonedTheDocumentIsManaged         int64 = 1
)

// ManagementServiceConfigurationConflictResolution allowed values.
const (
	ManagementServiceConfigurationConflictResolutionTheConflictResolutionIsOFF int64 = 0
	ManagementServiceConfigurationConflictResolutionTheConflictResolutionIsON  int64 = 1
)
