// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

// Package policyadmxwindowsmediaplayer binds the ADMX_WindowsMediaPlayer CSP (./Device/Vendor/MSFT/Policy/Config).
package policyadmxwindowsmediaplayer
