// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

package policyspeech

// AllowSpeechModelUpdate allowed values.
const (
	AllowSpeechModelUpdateNotAllowed int64 = 0
	AllowSpeechModelUpdateAllowed    int64 = 1
)
