// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

package policybitlocker

import csp "github.com/deploymenttheory/go-bindings-wmi/runtime/csp"

// EncryptionMethod: This policy specifies the BitLocker Drive Encryption method and cipher strength.
var EncryptionMethod = csp.Policy{
	Name:       "EncryptionMethod",
	URI:        "./Device/Vendor/MSFT/Policy/Config/Bitlocker/EncryptionMethod",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "6",
	MinOSBuild: "10.0.14393",
	CSPVersion: "4.1",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "Range"},
	Bridge:     &csp.Bridge{ConfigClass: "MDM_Policy_Config01_Bitlocker02", ResultClass: "MDM_Policy_Result01_Bitlocker02", InstanceID: "Bitlocker", ParentID: "./Vendor/MSFT/Policy/Config", Property: "EncryptionMethod"},
}

// All lists every policy in this CSP area.
var All = []csp.Policy{
	EncryptionMethod,
}
