// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

//go:build windows

package policysecurity

import (
	csp "github.com/deploymenttheory/go-bindings-wmi/runtime/csp"
	wmi "github.com/deploymenttheory/go-bindings-wmi/runtime/wmi"
)

// Service drives this CSP area's policies through the MDM bridge.
// Construct it with New, passing a wmi.Service connected to the bridge
// namespace (csp.Connect, which requires the SYSTEM account).
type Service struct{ svc *wmi.Service }

// New returns a Service bound to a connected bridge session.
func New(svc *wmi.Service) *Service { return &Service{svc: svc} }

// GetAllowAddProvisioningPackage reads the effective value of AllowAddProvisioningPackage.
func (s *Service) GetAllowAddProvisioningPackage() (int64, error) {
	v, err := csp.Read(s.svc, AllowAddProvisioningPackage)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetAllowAddProvisioningPackage sets AllowAddProvisioningPackage (OMA-DM Add/Replace).
func (s *Service) SetAllowAddProvisioningPackage(v int64) error {
	return csp.Set(s.svc, AllowAddProvisioningPackage, v)
}

// DeleteAllowAddProvisioningPackage unmanages AllowAddProvisioningPackage (OMA-DM Delete).
func (s *Service) DeleteAllowAddProvisioningPackage() error {
	return csp.Delete(s.svc, AllowAddProvisioningPackage)
}

// GetAllowManualRootCertificateInstallation reads the effective value of AllowManualRootCertificateInstallation.
func (s *Service) GetAllowManualRootCertificateInstallation() (int64, error) {
	v, err := csp.Read(s.svc, AllowManualRootCertificateInstallation)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetAllowManualRootCertificateInstallation sets AllowManualRootCertificateInstallation (OMA-DM Add/Replace).
func (s *Service) SetAllowManualRootCertificateInstallation(v int64) error {
	return csp.Set(s.svc, AllowManualRootCertificateInstallation, v)
}

// DeleteAllowManualRootCertificateInstallation unmanages AllowManualRootCertificateInstallation (OMA-DM Delete).
func (s *Service) DeleteAllowManualRootCertificateInstallation() error {
	return csp.Delete(s.svc, AllowManualRootCertificateInstallation)
}

// GetAllowRemoveProvisioningPackage reads the effective value of AllowRemoveProvisioningPackage.
func (s *Service) GetAllowRemoveProvisioningPackage() (int64, error) {
	v, err := csp.Read(s.svc, AllowRemoveProvisioningPackage)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetAllowRemoveProvisioningPackage sets AllowRemoveProvisioningPackage (OMA-DM Add/Replace).
func (s *Service) SetAllowRemoveProvisioningPackage(v int64) error {
	return csp.Set(s.svc, AllowRemoveProvisioningPackage, v)
}

// DeleteAllowRemoveProvisioningPackage unmanages AllowRemoveProvisioningPackage (OMA-DM Delete).
func (s *Service) DeleteAllowRemoveProvisioningPackage() error {
	return csp.Delete(s.svc, AllowRemoveProvisioningPackage)
}

// GetAntiTheftMode reads the effective value of AntiTheftMode.
func (s *Service) GetAntiTheftMode() (int64, error) {
	v, err := csp.Read(s.svc, AntiTheftMode)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetAntiTheftMode sets AntiTheftMode (OMA-DM Add/Replace).
func (s *Service) SetAntiTheftMode(v int64) error { return csp.Set(s.svc, AntiTheftMode, v) }

// DeleteAntiTheftMode unmanages AntiTheftMode (OMA-DM Delete).
func (s *Service) DeleteAntiTheftMode() error { return csp.Delete(s.svc, AntiTheftMode) }

// GetClearTPMIfNotReady reads the effective value of ClearTPMIfNotReady.
func (s *Service) GetClearTPMIfNotReady() (int64, error) {
	v, err := csp.Read(s.svc, ClearTPMIfNotReady)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetClearTPMIfNotReady sets ClearTPMIfNotReady (OMA-DM Add/Replace).
func (s *Service) SetClearTPMIfNotReady(v int64) error { return csp.Set(s.svc, ClearTPMIfNotReady, v) }

// DeleteClearTPMIfNotReady unmanages ClearTPMIfNotReady (OMA-DM Delete).
func (s *Service) DeleteClearTPMIfNotReady() error { return csp.Delete(s.svc, ClearTPMIfNotReady) }

// GetConfigureWindowsPasswords reads the effective value of ConfigureWindowsPasswords.
func (s *Service) GetConfigureWindowsPasswords() (int64, error) {
	v, err := csp.Read(s.svc, ConfigureWindowsPasswords)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetConfigureWindowsPasswords sets ConfigureWindowsPasswords (OMA-DM Add/Replace).
func (s *Service) SetConfigureWindowsPasswords(v int64) error {
	return csp.Set(s.svc, ConfigureWindowsPasswords, v)
}

// DeleteConfigureWindowsPasswords unmanages ConfigureWindowsPasswords (OMA-DM Delete).
func (s *Service) DeleteConfigureWindowsPasswords() error {
	return csp.Delete(s.svc, ConfigureWindowsPasswords)
}

// GetPreventAutomaticDeviceEncryptionForAzureADJoinedDevices reads the effective value of PreventAutomaticDeviceEncryptionForAzureADJoinedDevices.
func (s *Service) GetPreventAutomaticDeviceEncryptionForAzureADJoinedDevices() (int64, error) {
	v, err := csp.Read(s.svc, PreventAutomaticDeviceEncryptionForAzureADJoinedDevices)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetPreventAutomaticDeviceEncryptionForAzureADJoinedDevices sets PreventAutomaticDeviceEncryptionForAzureADJoinedDevices (OMA-DM Add/Replace).
func (s *Service) SetPreventAutomaticDeviceEncryptionForAzureADJoinedDevices(v int64) error {
	return csp.Set(s.svc, PreventAutomaticDeviceEncryptionForAzureADJoinedDevices, v)
}

// DeletePreventAutomaticDeviceEncryptionForAzureADJoinedDevices unmanages PreventAutomaticDeviceEncryptionForAzureADJoinedDevices (OMA-DM Delete).
func (s *Service) DeletePreventAutomaticDeviceEncryptionForAzureADJoinedDevices() error {
	return csp.Delete(s.svc, PreventAutomaticDeviceEncryptionForAzureADJoinedDevices)
}

// GetRecoveryEnvironmentAuthentication reads the effective value of RecoveryEnvironmentAuthentication.
func (s *Service) GetRecoveryEnvironmentAuthentication() (int64, error) {
	v, err := csp.Read(s.svc, RecoveryEnvironmentAuthentication)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetRecoveryEnvironmentAuthentication sets RecoveryEnvironmentAuthentication (OMA-DM Add/Replace).
func (s *Service) SetRecoveryEnvironmentAuthentication(v int64) error {
	return csp.Set(s.svc, RecoveryEnvironmentAuthentication, v)
}

// DeleteRecoveryEnvironmentAuthentication unmanages RecoveryEnvironmentAuthentication (OMA-DM Delete).
func (s *Service) DeleteRecoveryEnvironmentAuthentication() error {
	return csp.Delete(s.svc, RecoveryEnvironmentAuthentication)
}

// GetRequireDeviceEncryption reads the effective value of RequireDeviceEncryption.
func (s *Service) GetRequireDeviceEncryption() (int64, error) {
	v, err := csp.Read(s.svc, RequireDeviceEncryption)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetRequireDeviceEncryption sets RequireDeviceEncryption (OMA-DM Add/Replace).
func (s *Service) SetRequireDeviceEncryption(v int64) error {
	return csp.Set(s.svc, RequireDeviceEncryption, v)
}

// DeleteRequireDeviceEncryption unmanages RequireDeviceEncryption (OMA-DM Delete).
func (s *Service) DeleteRequireDeviceEncryption() error {
	return csp.Delete(s.svc, RequireDeviceEncryption)
}

// GetRequireProvisioningPackageSignature reads the effective value of RequireProvisioningPackageSignature.
func (s *Service) GetRequireProvisioningPackageSignature() (int64, error) {
	v, err := csp.Read(s.svc, RequireProvisioningPackageSignature)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetRequireProvisioningPackageSignature sets RequireProvisioningPackageSignature (OMA-DM Add/Replace).
func (s *Service) SetRequireProvisioningPackageSignature(v int64) error {
	return csp.Set(s.svc, RequireProvisioningPackageSignature, v)
}

// DeleteRequireProvisioningPackageSignature unmanages RequireProvisioningPackageSignature (OMA-DM Delete).
func (s *Service) DeleteRequireProvisioningPackageSignature() error {
	return csp.Delete(s.svc, RequireProvisioningPackageSignature)
}

// GetRequireRetrieveHealthCertificateOnBoot reads the effective value of RequireRetrieveHealthCertificateOnBoot.
func (s *Service) GetRequireRetrieveHealthCertificateOnBoot() (int64, error) {
	v, err := csp.Read(s.svc, RequireRetrieveHealthCertificateOnBoot)
	if err != nil {
		return 0, err
	}
	return wmi.AsInt64(v), nil
}

// SetRequireRetrieveHealthCertificateOnBoot sets RequireRetrieveHealthCertificateOnBoot (OMA-DM Add/Replace).
func (s *Service) SetRequireRetrieveHealthCertificateOnBoot(v int64) error {
	return csp.Set(s.svc, RequireRetrieveHealthCertificateOnBoot, v)
}

// DeleteRequireRetrieveHealthCertificateOnBoot unmanages RequireRetrieveHealthCertificateOnBoot (OMA-DM Delete).
func (s *Service) DeleteRequireRetrieveHealthCertificateOnBoot() error {
	return csp.Delete(s.svc, RequireRetrieveHealthCertificateOnBoot)
}
