// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

package policysearch

import csp "github.com/deploymenttheory/go-bindings-wmi/runtime/csp"

// AllowCloudSearch: Allow search and Cortana to search cloud sources like OneDrive and SharePoint. This policy allows corporate administrators to control whether employees can turn off/on the search of these cloud sources. The default policy value is to allow employees access to the setting that controls search of cloud sources.
var AllowCloudSearch = csp.Policy{
	Name:       "AllowCloudSearch",
	URI:        "./Device/Vendor/MSFT/Policy/Config/Search/AllowCloudSearch",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "1",
	MinOSBuild: "10.0.16299",
	CSPVersion: "6.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "0", Description: "Not allowed."}, {Value: "1", Description: "Allowed."}}},
}

// AllowCortanaInAAD: This features allows you to show the cortana opt-in page during Windows Setup
var AllowCortanaInAAD = csp.Policy{
	Name:       "AllowCortanaInAAD",
	URI:        "./Device/Vendor/MSFT/Policy/Config/Search/AllowCortanaInAAD",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "0",
	MinOSBuild: "10.0.17134",
	CSPVersion: "7.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "0", Description: "Not allowed. The Cortana consent page will not appear in AAD OOBE during setup."}, {Value: "1", Description: "Allowed. The Cortana consent page will appear in Azure AAD OOBE during setup."}}},
}

// AllowFindMyFiles: This feature allows you to disable find my files completely on the machine
var AllowFindMyFiles = csp.Policy{
	Name:       "AllowFindMyFiles",
	URI:        "./Device/Vendor/MSFT/Policy/Config/Search/AllowFindMyFiles",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "1",
	MinOSBuild: "10.0.18362",
	CSPVersion: "9.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "1", Description: "Find My Files feature can be toggled (still off by default), and the settings UI is present."}, {Value: "0", Description: "Find My Files feature is turned off completely, and the settings UI is disabled."}}},
}

// AllowIndexingEncryptedStoresOrItems: Allows or disallows the indexing of items. This switch is for the Windows Search Indexer, which controls whether it will index items that are encrypted, such as the Windows Information Protection (WIP) protected files. When the policy is enabled, WIP protected items are indexed and the metadata about them are stored in an unencrypted location. The metadata includes things like file path and date modified. When the policy is disabled, the WIP protected items are not indexed and do not show up in the results in Cortana or file explorer. There may also be a performance impact on photos and Groove apps if there are a lot of WIP protected media files on the device. Most restricted value is 0.
var AllowIndexingEncryptedStoresOrItems = csp.Policy{
	Name:       "AllowIndexingEncryptedStoresOrItems",
	URI:        "./Device/Vendor/MSFT/Policy/Config/Search/AllowIndexingEncryptedStoresOrItems",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "0",
	MinOSBuild: "10.0.14393",
	CSPVersion: "4.1",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "0", Description: "Not allowed."}, {Value: "1", Description: "Allowed."}}},
}

var AllowSearchHighlights = csp.Policy{
	Name:       "AllowSearchHighlights",
	URI:        "./Device/Vendor/MSFT/Policy/Config/Search/AllowSearchHighlights",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "1",
	MinOSBuild: "10.0.22621, 10.0.22000.1761, 10.0.19044.1620, 10.0.19043.1620, 10.0.19042.1620",
	CSPVersion: "10.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "Range"},
}

// AllowSearchToUseLocation: Specifies whether search can leverage location information. Most restricted value is 0.
var AllowSearchToUseLocation = csp.Policy{
	Name:       "AllowSearchToUseLocation",
	URI:        "./Device/Vendor/MSFT/Policy/Config/Search/AllowSearchToUseLocation",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "1",
	MinOSBuild: "10.0.10240",
	CSPVersion: "1.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x88;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "0", Description: "Not allowed."}, {Value: "1", Description: "Allowed."}}},
}

// AllowStoringImagesFromVisionSearch: This policy has been deprecated.
var AllowStoringImagesFromVisionSearch = csp.Policy{
	Name:       "AllowStoringImagesFromVisionSearch",
	URI:        "./Device/Vendor/MSFT/Policy/Config/Search/AllowStoringImagesFromVisionSearch",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "1",
	MinOSBuild: "10.0.10240",
	CSPVersion: "1.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "0", Description: "Not allowed."}, {Value: "1", Description: "Allowed."}}},
}

// AllowUsingDiacritics: Allows the use of diacritics. Most restricted value is 0.
var AllowUsingDiacritics = csp.Policy{
	Name:       "AllowUsingDiacritics",
	URI:        "./Device/Vendor/MSFT/Policy/Config/Search/AllowUsingDiacritics",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "0",
	MinOSBuild: "10.0.14393",
	CSPVersion: "4.1",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "0", Description: "Not allowed."}, {Value: "1", Description: "Allowed."}}},
}

// AllowWindowsIndexer: Allow Windows indexer. Value type is integer.
var AllowWindowsIndexer = csp.Policy{
	Name:       "AllowWindowsIndexer",
	URI:        "./Device/Vendor/MSFT/Policy/Config/Search/AllowWindowsIndexer",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "3",
	MinOSBuild: "10.0.10240",
	CSPVersion: "1.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "Range"},
}

// AlwaysUseAutoLangDetection: Specifies whether to always use automatic language detection when indexing content and properties. Most restricted value is 0.
var AlwaysUseAutoLangDetection = csp.Policy{
	Name:       "AlwaysUseAutoLangDetection",
	URI:        "./Device/Vendor/MSFT/Policy/Config/Search/AlwaysUseAutoLangDetection",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "0",
	MinOSBuild: "10.0.14393",
	CSPVersion: "4.1",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "0", Description: "Not allowed."}, {Value: "1", Description: "Allowed."}}},
}

// ConfigureSearchOnTaskbarMode: Configures search on the taskbar. If you disable this policy setting or do not configure it, users can see and change this setting.
var ConfigureSearchOnTaskbarMode = csp.Policy{
	Name:       "ConfigureSearchOnTaskbarMode",
	URI:        "./Device/Vendor/MSFT/Policy/Config/Search/ConfigureSearchOnTaskbarMode",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "3",
	MinOSBuild: "10.0.26100",
	CSPVersion: "11.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "0", Description: "Hide"}, {Value: "1", Description: "Search icon only"}, {Value: "2", Description: "Search icon and label"}, {Value: "3", Description: "Search box"}}},
}

// DisableBackoff: If enabled, the search indexer backoff feature will be disabled. Indexing will continue at full speed even when system activity is high. If disabled, backoff logic will be used to throttle back indexing activity when system activity is high. Default is disabled.
var DisableBackoff = csp.Policy{
	Name:       "DisableBackoff",
	URI:        "./Device/Vendor/MSFT/Policy/Config/Search/DisableBackoff",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "0",
	MinOSBuild: "10.0.14393",
	CSPVersion: "4.1",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "0", Description: "Disable."}, {Value: "1", Description: "Enable."}}},
}

// DisableRemovableDriveIndexing: This policy setting configures whether or not locations on removable drives can be added to libraries. If you enable this policy setting, locations on removable drives cannot be added to libraries. In addition, locations on removable drives cannot be indexed. If you disable or do not configure this policy setting, locations on removable drives can be added to libraries. In addition, locations on removable drives can be indexed.
var DisableRemovableDriveIndexing = csp.Policy{
	Name:       "DisableRemovableDriveIndexing",
	URI:        "./Device/Vendor/MSFT/Policy/Config/Search/DisableRemovableDriveIndexing",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "0",
	MinOSBuild: "10.0.14393",
	CSPVersion: "4.1",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "0", Description: "Disable."}, {Value: "1", Description: "Enable."}}},
}

// DisableSearch: Enabling this policy completely disables Search UI and all its entry points such as keyboard shortcuts and touchpad gestures. It removes the Search button from the Taskbar and the corresponding option in the Settings. It also disables type-to-search in the Start menu and removes the Start menu's search box.
var DisableSearch = csp.Policy{
	Name:       "DisableSearch",
	URI:        "./Device/Vendor/MSFT/Policy/Config/Search/DisableSearch",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "0",
	MinOSBuild: "10.0.22621",
	CSPVersion: "11.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "0", Description: "Do not disable."}, {Value: "1", Description: "Disable."}}},
}

// DoNotUseWebResults: Don't search the web or display web results in Search. This policy setting allows you to control whether or not Search can perform queries on the web, and if the web results are displayed in Search. If you enable this policy setting, queries won't be performed on the web and web results won't be displayed when a user performs a query in Search. If you disable this policy setting, queries will be performed on the web and web results will be displayed when a user performs a query in Search.
var DoNotUseWebResults = csp.Policy{
	Name:       "DoNotUseWebResults",
	URI:        "./Device/Vendor/MSFT/Policy/Config/Search/DoNotUseWebResults",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "1",
	MinOSBuild: "10.0.17134",
	CSPVersion: "7.0",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "0", Description: "Not allowed. Queries won't be performed on the web and web results won't be displayed when a user performs a query in Search."}, {Value: "1", Description: "Allowed. Queries will be performed on the web and web results will be displayed when a user performs a query in Search."}}},
}

// PreventIndexingLowDiskSpaceMB: Enabling this policy prevents indexing from continuing after less than the specified amount of hard drive space is left on the same drive as the index location. Select between 0 and 1. Enable this policy if computers in your environment have extremely limited hard drive space. When this policy is disabled or not configured, Windows Desktop Search automatically manages your index size.
var PreventIndexingLowDiskSpaceMB = csp.Policy{
	Name:       "PreventIndexingLowDiskSpaceMB",
	URI:        "./Device/Vendor/MSFT/Policy/Config/Search/PreventIndexingLowDiskSpaceMB",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "1",
	MinOSBuild: "10.0.14393",
	CSPVersion: "4.1",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "0", Description: "Disable."}, {Value: "1", Description: "Enable."}}},
}

// PreventRemoteQueries: If enabled, clients will be unable to query this computer's index remotely. Thus, when they are browsing network shares that are stored on this computer, they will not search them using the index. If disabled, client search requests will use this computer's index. .
var PreventRemoteQueries = csp.Policy{
	Name:       "PreventRemoteQueries",
	URI:        "./Device/Vendor/MSFT/Policy/Config/Search/PreventRemoteQueries",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "1",
	MinOSBuild: "10.0.14393",
	CSPVersion: "4.1",
	Editions:   "0x4;0x1B;0x30;0x31;0x48;0x54;0x79;0x7A;0x7D;0x7E;0x81;0x82;0x8A;0x8B;0xA1;0xA2;0xA4;0xA5;0xAB;0xAC;0xAF;0xBC;0xBF;0xCA;0xCB;0xCD;0xCF;",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "0", Description: "Disable."}, {Value: "1", Description: "Enable."}}},
}

// SafeSearchPermissions: This policy is deprecated.
// Deprecated: as of OS build 10.0.22000.
var SafeSearchPermissions = csp.Policy{
	Name:              "SafeSearchPermissions",
	URI:               "./Device/Vendor/MSFT/Policy/Config/Search/SafeSearchPermissions",
	Format:            "int",
	Access:            []string{"Add", "Delete", "Get", "Replace"},
	Default:           "1",
	DeprecatedOSBuild: "10.0.22000",
	MinOSBuild:        "10.0.14393",
	CSPVersion:        "4.1",
	Allowed:           &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "1", Description: "Enable"}, {Value: "0", Description: "Disable"}}},
}

// All lists every policy in this CSP area.
var All = []csp.Policy{
	AllowCloudSearch,
	AllowCortanaInAAD,
	AllowFindMyFiles,
	AllowIndexingEncryptedStoresOrItems,
	AllowSearchHighlights,
	AllowSearchToUseLocation,
	AllowStoringImagesFromVisionSearch,
	AllowUsingDiacritics,
	AllowWindowsIndexer,
	AlwaysUseAutoLangDetection,
	ConfigureSearchOnTaskbarMode,
	DisableBackoff,
	DisableRemovableDriveIndexing,
	DisableSearch,
	DoNotUseWebResults,
	PreventIndexingLowDiskSpaceMB,
	PreventRemoteQueries,
	SafeSearchPermissions,
}
