// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

package policybits

// CostedNetworkBehaviorBackgroundPriority allowed values.
const (
	CostedNetworkBehaviorBackgroundPriorityAlwaysTransfer                                        int64 = 1
	CostedNetworkBehaviorBackgroundPriorityTransferUnlessRoaming                                 int64 = 2
	CostedNetworkBehaviorBackgroundPriorityTransferUnlessSurchargeAppliesWhenNotRoamingOrOverCap int64 = 3
	CostedNetworkBehaviorBackgroundPriorityTransferUnlessNearingLimitWhenNotRoamingOrNearingCap  int64 = 4
	CostedNetworkBehaviorBackgroundPriorityTransferOnlyIfUnconstrained                           int64 = 5
)

// CostedNetworkBehaviorForegroundPriority allowed values.
const (
	CostedNetworkBehaviorForegroundPriorityAlwaysTransfer                                        int64 = 1
	CostedNetworkBehaviorForegroundPriorityTransferUnlessRoaming                                 int64 = 2
	CostedNetworkBehaviorForegroundPriorityTransferUnlessSurchargeAppliesWhenNotRoamingOrOverCap int64 = 3
	CostedNetworkBehaviorForegroundPriorityTransferUnlessNearingLimitWhenNotRoamingOrNearingCap  int64 = 4
	CostedNetworkBehaviorForegroundPriorityTransferOnlyIfUnconstrained                           int64 = 5
)
