// Code generated by go-bindings-wmi-csp-codegen. DO NOT EDIT.

package vpnv2

import csp "github.com/deploymenttheory/go-bindings-wmi/runtime/csp"

// APNBindingAccessPointName: Reserved for future use.
var APNBindingAccessPointName = csp.Policy{
	Name:   "AccessPointName",
	URI:    "./Device/Vendor/MSFT/VPNv2/APNBinding/AccessPointName",
	Format: "chr",
	Access: []string{"Add", "Delete", "Get", "Replace"},
}

// APNBindingAuthenticationType: Reserved for future use.
var APNBindingAuthenticationType = csp.Policy{
	Name:   "AuthenticationType",
	URI:    "./Device/Vendor/MSFT/VPNv2/APNBinding/AuthenticationType",
	Format: "chr",
	Access: []string{"Add", "Delete", "Get", "Replace"},
}

// APNBindingIsCompressionEnabled: Reserved for future use.
var APNBindingIsCompressionEnabled = csp.Policy{
	Name:   "IsCompressionEnabled",
	URI:    "./Device/Vendor/MSFT/VPNv2/APNBinding/IsCompressionEnabled",
	Format: "bool",
	Access: []string{"Add", "Delete", "Get", "Replace"},
}

// APNBindingPassword: Reserved for future use.
var APNBindingPassword = csp.Policy{
	Name:   "Password",
	URI:    "./Device/Vendor/MSFT/VPNv2/APNBinding/Password",
	Format: "chr",
	Access: []string{"Add", "Delete", "Get", "Replace"},
}

// APNBindingProviderId: Reserved for future use.
var APNBindingProviderId = csp.Policy{
	Name:   "ProviderId",
	URI:    "./Device/Vendor/MSFT/VPNv2/APNBinding/ProviderId",
	Format: "chr",
	Access: []string{"Add", "Delete", "Get", "Replace"},
}

// APNBindingUserName: Reserved for future use.
var APNBindingUserName = csp.Policy{
	Name:   "UserName",
	URI:    "./Device/Vendor/MSFT/VPNv2/APNBinding/UserName",
	Format: "chr",
	Access: []string{"Add", "Delete", "Get", "Replace"},
}

// AlwaysOn: An optional flag to enable Always On mode. This will automatically connect the VPN at sign-in and will stay connected until the user manually disconnects.
var AlwaysOn = csp.Policy{
	Name:    "AlwaysOn",
	URI:     "./Device/Vendor/MSFT/VPNv2/AlwaysOn",
	Format:  "bool",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Default: "false",
	Allowed: &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "false", Description: "Always On is turned off."}, {Value: "true", Description: "Always On is turned on."}}},
}

// AlwaysOnActive: An optional flag to activate Always On mode. This is true by default if AlwaysOn is true. Setting controls whether "Connect Automatically" is toggled on profile creation.
var AlwaysOnActive = csp.Policy{
	Name:    "AlwaysOnActive",
	URI:     "./Device/Vendor/MSFT/VPNv2/AlwaysOnActive",
	Format:  "bool",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Default: "1",
	Allowed: &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "0", Description: "Always On is inactive."}, {Value: "1", Description: "Always On is activated on provisioning."}}},
}

// AppTriggerListAppId: App Identity. Specified, based on the Type Field.
var AppTriggerListAppId = csp.Policy{
	Name:    "Id",
	URI:     "./Device/Vendor/MSFT/VPNv2/AppTriggerList/App/Id",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "None"},
}

// AppTriggerListAppType: Returns the type of App/Id. This value can be either of the following: PackageFamilyName - When this is returned, the App/Id value represents the PackageFamilyName of the app. The PackageFamilyName is the unique name of the Microsoft Store application. FilePath - When this is returned, the App/Id value represents the full file path of the app. For example, C:\Windows\System\Notepad.exe.
var AppTriggerListAppType = csp.Policy{
	Name:   "Type",
	URI:    "./Device/Vendor/MSFT/VPNv2/AppTriggerList/App/Type",
	Format: "chr",
	Access: []string{"Get"},
}

// ByPassForLocal: Not supported.
var ByPassForLocal = csp.Policy{
	Name:   "ByPassForLocal",
	URI:    "./Device/Vendor/MSFT/VPNv2/ByPassForLocal",
	Format: "bool",
	Access: []string{"Add", "Delete", "Get", "Replace"},
}

// DataEncryption: Determines the level of data encryption required for the connection.
var DataEncryption = csp.Policy{
	Name:       "DataEncryption",
	URI:        "./Device/Vendor/MSFT/VPNv2/DataEncryption",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "Require",
	MinOSBuild: "10.0.22000",
	CSPVersion: "1.6",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "None", Description: "No Data Encryption required."}, {Value: "Require", Description: "Data Encryption required."}, {Value: "Max", Description: "Maximum-strength Data Encryption required."}, {Value: "Optional", Description: "Perform encryption if possible."}}},
}

// DeviceComplianceEnabled: Enables the Device Compliance flow from the client. If marked as True, the VPN Client will attempt to communicate with AAD to get a certificate to use for authentication. The VPN should be set up to use Certificate Auth and the VPN Server must trust the Server returned by Azure Active Directory.
var DeviceComplianceEnabled = csp.Policy{
	Name:    "Enabled",
	URI:     "./Device/Vendor/MSFT/VPNv2/DeviceCompliance/Enabled",
	Format:  "bool",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "false", Description: "Disabled"}, {Value: "true", Description: "Enabled"}}},
}

// DeviceComplianceSsoEku: Comma Separated list of EKU's for the VPN Client to look for the correct certificate for Kerberos Authentication.
var DeviceComplianceSsoEku = csp.Policy{
	Name:    "Eku",
	URI:     "./Device/Vendor/MSFT/VPNv2/DeviceCompliance/Sso/Eku",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "None"},
}

// DeviceComplianceSsoEnabled: If this field is set to True the VPN Client will look for a separate certificate for Kerberos Authentication.
var DeviceComplianceSsoEnabled = csp.Policy{
	Name:    "Enabled",
	URI:     "./Device/Vendor/MSFT/VPNv2/DeviceCompliance/Sso/Enabled",
	Format:  "bool",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "false", Description: "Disabled"}, {Value: "true", Description: "Enabled"}}},
}

// DeviceComplianceSsoIssuerHash: Comma Separated list of Issuer Hashes for the VPN Client to look for the correct certificate for Kerberos Authentication.
var DeviceComplianceSsoIssuerHash = csp.Policy{
	Name:    "IssuerHash",
	URI:     "./Device/Vendor/MSFT/VPNv2/DeviceCompliance/Sso/IssuerHash",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "None"},
}

// DisableAdvancedOptionsEditButton: Optional. When this setting is True, the Advanced Options page will have its edit functions disabled, only allowing viewing and Clear Sign-In Info.
var DisableAdvancedOptionsEditButton = csp.Policy{
	Name:       "DisableAdvancedOptionsEditButton",
	URI:        "./Device/Vendor/MSFT/VPNv2/DisableAdvancedOptionsEditButton",
	Format:     "bool",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000",
	CSPVersion: "1.5",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "false", Description: "Advanced Options Edit Button is available."}, {Value: "true", Description: "Advanced Options Edit Button is unavailable."}}},
}

// DisableDisconnectButton: Optional. When this setting is True, the Disconnect button will not be visible for connected profiles and the 'Connect automatically' checkbox cannot be deselected.
var DisableDisconnectButton = csp.Policy{
	Name:       "DisableDisconnectButton",
	URI:        "./Device/Vendor/MSFT/VPNv2/DisableDisconnectButton",
	Format:     "bool",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000",
	CSPVersion: "1.5",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "false", Description: "Disconnect Button is visible."}, {Value: "true", Description: "Disconnect Button is not visible."}}},
}

// DisableIKEv2Fragmentation: Set to disable IKEv2 Fragmentation.
var DisableIKEv2Fragmentation = csp.Policy{
	Name:       "DisableIKEv2Fragmentation",
	URI:        "./Device/Vendor/MSFT/VPNv2/DisableIKEv2Fragmentation",
	Format:     "bool",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "false",
	MinOSBuild: "10.0.22000",
	CSPVersion: "1.6",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "true", Description: "IKEv2 Fragmentation will not be used."}, {Value: "false", Description: "IKEv2 Fragmentation is used as normal."}}},
}

// DnsSuffix: Specifies one or more comma separated DNS suffixes. The first in the list is also used as the primary connection specific DNS suffix for the VPN Interface. The entire list will also be added into the SuffixSearchList.
var DnsSuffix = csp.Policy{
	Name:    "DnsSuffix",
	URI:     "./Device/Vendor/MSFT/VPNv2/DnsSuffix",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "None"},
}

// DomainNameInformationListAutoTrigger: Boolean to determine whether this domain name rule will trigger the VPN.
var DomainNameInformationListAutoTrigger = csp.Policy{
	Name:       "AutoTrigger",
	URI:        "./Device/Vendor/MSFT/VPNv2/DomainNameInformationList/AutoTrigger",
	Format:     "bool",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "false",
	MinOSBuild: "10.0.14393",
	CSPVersion: "1.2",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "false", Description: "This DomainName rule will not trigger the VPN."}, {Value: "true", Description: "This DomainName rule will trigger the VPN."}}},
}

// DomainNameInformationListDnsServers: Comma Seperated list of IP addresses for the DNS Servers to use for the domain name.
var DomainNameInformationListDnsServers = csp.Policy{
	Name:    "DnsServers",
	URI:     "./Device/Vendor/MSFT/VPNv2/DomainNameInformationList/DnsServers",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "None"},
}

// DomainNameInformationListDomainName: Used to indicate the namespace to which the policy applies. When a Name query is issued, the DNS client compares the name in the query to all of the namespaces under DomainNameInformationList to find a match. This parameter can be one of the following types: FQDN - Fully qualified domain name. Suffix - A domain suffix that will be appended to the shortname query for DNS resolution. To specify a suffix, prepend a . to the DNS suffix.
var DomainNameInformationListDomainName = csp.Policy{
	Name:    "DomainName",
	URI:     "./Device/Vendor/MSFT/VPNv2/DomainNameInformationList/DomainName",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "None"},
}

// DomainNameInformationListDomainNameType: Returns the namespace type. This value can be one of the following: FQDN - If the DomainName was not prepended with a . and applies only to the fully qualified domain name (FQDN) of a specified host. Suffix - If the DomainName was prepended with a . and applies to the specified namespace, all records in that namespace, and all subdomains.
var DomainNameInformationListDomainNameType = csp.Policy{
	Name:   "DomainNameType",
	URI:    "./Device/Vendor/MSFT/VPNv2/DomainNameInformationList/DomainNameType",
	Format: "chr",
	Access: []string{"Get"},
}

// DomainNameInformationListPersistent: A boolean value that specifies if the rule being added should persist even when the VPN is not connected.
var DomainNameInformationListPersistent = csp.Policy{
	Name:       "Persistent",
	URI:        "./Device/Vendor/MSFT/VPNv2/DomainNameInformationList/Persistent",
	Format:     "bool",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "false",
	MinOSBuild: "10.0.14393",
	CSPVersion: "1.2",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "false", Description: "This DomainName rule will only be applied when VPN is connected."}, {Value: "true", Description: "This DomainName rule will always be present and applied."}}},
}

// DomainNameInformationListWebProxyServers: Web Proxy Server IP address if you are redirecting traffic through your intranet.
var DomainNameInformationListWebProxyServers = csp.Policy{
	Name:    "WebProxyServers",
	URI:     "./Device/Vendor/MSFT/VPNv2/DomainNameInformationList/WebProxyServers",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "None"},
}

// EdpModeId: Enterprise ID, which is required for connecting this VPN profile with an WIP policy. When this is set, the networking stack looks for this Enterprise ID in the app token to determine if the traffic is allowed to go over the VPN. If the profile is active, it also automatically triggers the VPN to connect. We recommend having only one such profile per device.
var EdpModeId = csp.Policy{
	Name:    "EdpModeId",
	URI:     "./Device/Vendor/MSFT/VPNv2/EdpModeId",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "None"},
}

// IPv4InterfaceMetric: The metric for the IPv4 interface.
var IPv4InterfaceMetric = csp.Policy{
	Name:       "IPv4InterfaceMetric",
	URI:        "./Device/Vendor/MSFT/VPNv2/IPv4InterfaceMetric",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000",
	CSPVersion: "1.6",
	Allowed:    &csp.Allowed{Type: "Range"},
}

// IPv6InterfaceMetric: The metric for the IPv6 interface.
var IPv6InterfaceMetric = csp.Policy{
	Name:       "IPv6InterfaceMetric",
	URI:        "./Device/Vendor/MSFT/VPNv2/IPv6InterfaceMetric",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000",
	CSPVersion: "1.6",
	Allowed:    &csp.Allowed{Type: "Range"},
}

// NativeProfileAuthenticationCertificateEku: Reserved for future use.
var NativeProfileAuthenticationCertificateEku = csp.Policy{
	Name:   "Eku",
	URI:    "./Device/Vendor/MSFT/VPNv2/NativeProfile/Authentication/Certificate/Eku",
	Format: "chr",
	Access: []string{"Add", "Delete", "Get", "Replace"},
}

// NativeProfileAuthenticationCertificateIssuer: Reserved for future use.
var NativeProfileAuthenticationCertificateIssuer = csp.Policy{
	Name:   "Issuer",
	URI:    "./Device/Vendor/MSFT/VPNv2/NativeProfile/Authentication/Certificate/Issuer",
	Format: "chr",
	Access: []string{"Add", "Delete", "Get", "Replace"},
}

// NativeProfileAuthenticationEapConfiguration: HTML encoded XML of the EAP configuration. For more information about EAP configuration XML, see https://docs.microsoft.com/en-us/windows/client-management/mdm/eap-configuration.
var NativeProfileAuthenticationEapConfiguration = csp.Policy{
	Name:    "Configuration",
	URI:     "./Device/Vendor/MSFT/VPNv2/NativeProfile/Authentication/Eap/Configuration",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "None"},
}

// NativeProfileAuthenticationEapType: Required node for EAP profiles. This specifies the EAP Type ID
var NativeProfileAuthenticationEapType = csp.Policy{
	Name:    "Type",
	URI:     "./Device/Vendor/MSFT/VPNv2/NativeProfile/Authentication/Eap/Type",
	Format:  "int",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "None"},
}

// NativeProfileAuthenticationMachineMethod: This is only supported in IKEv2.
var NativeProfileAuthenticationMachineMethod = csp.Policy{
	Name:    "MachineMethod",
	URI:     "./Device/Vendor/MSFT/VPNv2/NativeProfile/Authentication/MachineMethod",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "Certificate", Description: "Certificate"}}},
}

// NativeProfileAuthenticationUserMethod: This value can be one of the following: EAP or MSChapv2 (This is not supported for IKEv2).
var NativeProfileAuthenticationUserMethod = csp.Policy{
	Name:    "UserMethod",
	URI:     "./Device/Vendor/MSFT/VPNv2/NativeProfile/Authentication/UserMethod",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "EAP", Description: "EAP"}, {Value: "MSChapv2", Description: "MSChapv2: This is not supported for IKEv2"}}},
}

// NativeProfileCryptographySuiteAuthenticationTransformConstants: Type of authentication transform constant.
var NativeProfileCryptographySuiteAuthenticationTransformConstants = csp.Policy{
	Name:    "AuthenticationTransformConstants",
	URI:     "./Device/Vendor/MSFT/VPNv2/NativeProfile/CryptographySuite/AuthenticationTransformConstants",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "MD596", Description: "MD596"}, {Value: "SHA196", Description: "SHA196"}, {Value: "SHA256128", Description: "SHA256128"}, {Value: "GCMAES128", Description: "GCMAES128"}, {Value: "GCMAES192", Description: "GCMAES192"}, {Value: "GCMAES256", Description: "GCMAES256"}}},
}

// NativeProfileCryptographySuiteCipherTransformConstants: Type of Cipher transform constant.
var NativeProfileCryptographySuiteCipherTransformConstants = csp.Policy{
	Name:    "CipherTransformConstants",
	URI:     "./Device/Vendor/MSFT/VPNv2/NativeProfile/CryptographySuite/CipherTransformConstants",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "DES", Description: "DES"}, {Value: "DES3", Description: "DES3"}, {Value: "AES128", Description: "AES128"}, {Value: "AES192", Description: "AES192"}, {Value: "AES256", Description: "AES256"}, {Value: "GCMAES128", Description: "GCMAES128"}, {Value: "GCMAES192", Description: "GCMAES192"}, {Value: "GCMAES256", Description: "GCMAES256"}}},
}

// NativeProfileCryptographySuiteDHGroup: Group used for DH (Diffie-Hellman).
var NativeProfileCryptographySuiteDHGroup = csp.Policy{
	Name:    "DHGroup",
	URI:     "./Device/Vendor/MSFT/VPNv2/NativeProfile/CryptographySuite/DHGroup",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "None", Description: "None"}, {Value: "Group1", Description: "Group1"}, {Value: "Group2", Description: "Group2"}, {Value: "Group14", Description: "Group14"}, {Value: "ECP256", Description: "ECP256"}, {Value: "ECP384", Description: "ECP384"}, {Value: "Group24", Description: "Group24"}}},
}

// NativeProfileCryptographySuiteEncryptionMethod: Type of encryption method.
var NativeProfileCryptographySuiteEncryptionMethod = csp.Policy{
	Name:    "EncryptionMethod",
	URI:     "./Device/Vendor/MSFT/VPNv2/NativeProfile/CryptographySuite/EncryptionMethod",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "DES", Description: "DES"}, {Value: "DES3", Description: "DES3"}, {Value: "AES128", Description: "AES128"}, {Value: "AES192", Description: "AES192"}, {Value: "AES256", Description: "AES256"}, {Value: "AES_GCM_128", Description: "AES_GCM_128"}, {Value: "AES_GCM_256", Description: "AES_GCM_256"}}},
}

// NativeProfileCryptographySuiteIntegrityCheckMethod: Type of integrity check.
var NativeProfileCryptographySuiteIntegrityCheckMethod = csp.Policy{
	Name:    "IntegrityCheckMethod",
	URI:     "./Device/Vendor/MSFT/VPNv2/NativeProfile/CryptographySuite/IntegrityCheckMethod",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "MD5", Description: "MD5"}, {Value: "SHA196", Description: "SHA196"}, {Value: "SHA256", Description: "SHA256"}, {Value: "SHA384", Description: "SHA384"}}},
}

// NativeProfileCryptographySuitePfsGroup: Group used for PFS (Perfect Forward Secrecy).
var NativeProfileCryptographySuitePfsGroup = csp.Policy{
	Name:    "PfsGroup",
	URI:     "./Device/Vendor/MSFT/VPNv2/NativeProfile/CryptographySuite/PfsGroup",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "None", Description: "None"}, {Value: "PFS1", Description: "PFS1"}, {Value: "PFS2", Description: "PFS2"}, {Value: "PFS2048", Description: "PFS2048"}, {Value: "ECP256", Description: "ECP256"}, {Value: "ECP384", Description: "ECP384"}, {Value: "PFSMM", Description: "PFSMM"}, {Value: "PFS24", Description: "PFS24"}}},
}

// NativeProfileDisableClassBasedDefaultRoute: Specifies the class based default routes. For example, if the interface IP begins with 10, it assumes a class a IP and pushes the route to 10.0.0.0/8
var NativeProfileDisableClassBasedDefaultRoute = csp.Policy{
	Name:       "DisableClassBasedDefaultRoute",
	URI:        "./Device/Vendor/MSFT/VPNv2/NativeProfile/DisableClassBasedDefaultRoute",
	Format:     "bool",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.14393",
	CSPVersion: "1.2",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "false", Description: "Enabled"}, {Value: "true", Description: "Disabled"}}},
}

// NativeProfileL2tpPsk: The preshared key used for an L2TP connection.
var NativeProfileL2tpPsk = csp.Policy{
	Name:       "L2tpPsk",
	URI:        "./Device/Vendor/MSFT/VPNv2/NativeProfile/L2tpPsk",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.14393",
	CSPVersion: "1.2",
	Allowed:    &csp.Allowed{Type: "None"},
}

// NativeProfileNativeProtocolType: Required for native profiles. Type of tunneling protocol used.
var NativeProfileNativeProtocolType = csp.Policy{
	Name:    "NativeProtocolType",
	URI:     "./Device/Vendor/MSFT/VPNv2/NativeProfile/NativeProtocolType",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "PPTP", Description: "PPTP"}, {Value: "L2TP", Description: "L2TP"}, {Value: "IKEv2", Description: "IKEv2"}, {Value: "Automatic", Description: "Automatic"}, {Value: "SSTP", Description: "SSTP"}, {Value: "ProtocolList", Description: "ProtocolList"}}},
}

// NativeProfilePlumbIKEv2TSAsRoutes: True: Plumb traffic selectors as routes onto VPN interface, False: Do not plumb traffic selectors as routes.
var NativeProfilePlumbIKEv2TSAsRoutes = csp.Policy{
	Name:       "PlumbIKEv2TSAsRoutes",
	URI:        "./Device/Vendor/MSFT/VPNv2/NativeProfile/PlumbIKEv2TSAsRoutes",
	Format:     "bool",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.19041",
	CSPVersion: "1.3",
}

// NativeProfileProtocolListNativeProtocolListType: Inbox VPN protocols type.
var NativeProfileProtocolListNativeProtocolListType = csp.Policy{
	Name:    "Type",
	URI:     "./Device/Vendor/MSFT/VPNv2/NativeProfile/ProtocolList/NativeProtocolList/Type",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "Pptp", Description: "Pptp"}, {Value: "L2tp", Description: "L2tp"}, {Value: "Ikev2", Description: "Ikev2"}, {Value: "Sstp", Description: "Sstp"}}},
}

// NativeProfileProtocolListRetryTimeInHours: Default 168, max 500000.
var NativeProfileProtocolListRetryTimeInHours = csp.Policy{
	Name:   "RetryTimeInHours",
	URI:    "./Device/Vendor/MSFT/VPNv2/NativeProfile/ProtocolList/RetryTimeInHours",
	Format: "int",
	Access: []string{"Add", "Delete", "Get", "Replace"},
}

// NativeProfileRoutingPolicyType: Type of routing policy.
var NativeProfileRoutingPolicyType = csp.Policy{
	Name:    "RoutingPolicyType",
	URI:     "./Device/Vendor/MSFT/VPNv2/NativeProfile/RoutingPolicyType",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "SplitTunnel", Description: "Traffic can go over any interface as determined by the networking stack."}, {Value: "ForceTunnel", Description: "All IP traffic must go over the VPN interface."}}},
}

// NativeProfileServers: Required for native profiles. Public or routable IP address or DNS name for the VPN gateway. It can point to the external IP of a gateway or a virtual IP for a server farm. Examples, 208.147.66.130 or vpn.contoso.com. The name can be a server name plus a friendly name separated with a semi-colon. For example, server2.example.com;server2FriendlyName. When you get the value, the return will include both the server name and the friendly name; if no friendly name had been supplied it will default to the server name. You can make a list of server names (with optional friendly names) separated by commas. For example, server1.example.com,server2.example.com. If the user is using the native Windows VPN client, they will then be able to select between servers. Only the chosen server will be used for connections, the options will not be iterated automatically.
var NativeProfileServers = csp.Policy{
	Name:   "Servers",
	URI:    "./Device/Vendor/MSFT/VPNv2/NativeProfile/Servers",
	Format: "chr",
	Access: []string{"Add", "Delete", "Get", "Replace"},
}

// NetworkOutageTime: Optional. For IKEv2 VPN connections only. Specifies the amount of time in seconds the VPN client will wait to notify the network stack if the VPN server becomes unavailable. This allows the VPN connection to survive when the client changes its connectivity, e.g. because of switching from LAN to MBN, or when the client is disconnected for some time, e.g. sitting in a train that runs through a tunnel. It's recommended to set this value between 0 and 28,800 seconds (8 hours).
var NetworkOutageTime = csp.Policy{
	Name:       "NetworkOutageTime",
	URI:        "./Device/Vendor/MSFT/VPNv2/NetworkOutageTime",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.22000",
	CSPVersion: "1.6",
	Allowed:    &csp.Allowed{Type: "Range"},
}

// PluginProfileCustomConfiguration: Optional. This is an HTML encoded XML blob for SSL-VPN plug-in specific configuration including authentication information that is deployed to the device to make it available for SSL-VPN plug-ins. Contact the plugin provider for format and other details. Most plugins can also configure values based on the server negotiations as well as defaults.
var PluginProfileCustomConfiguration = csp.Policy{
	Name:    "CustomConfiguration",
	URI:     "./Device/Vendor/MSFT/VPNv2/PluginProfile/CustomConfiguration",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "None"},
}

// PluginProfilePluginPackageFamilyName: Required for Plugin Profiles. This node specifies the Package Family Name of the SSL-VPN plugin app.
var PluginProfilePluginPackageFamilyName = csp.Policy{
	Name:    "PluginPackageFamilyName",
	URI:     "./Device/Vendor/MSFT/VPNv2/PluginProfile/PluginPackageFamilyName",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "None"},
}

// PluginProfileServerUrlList: Required for plug-in profiles. Semicolon-separated list of servers in URL, hostname, or IP format.
var PluginProfileServerUrlList = csp.Policy{
	Name:    "ServerUrlList",
	URI:     "./Device/Vendor/MSFT/VPNv2/PluginProfile/ServerUrlList",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "None"},
}

// PrivateNetwork: Determines whether the VPN connection is public or private.
var PrivateNetwork = csp.Policy{
	Name:       "PrivateNetwork",
	URI:        "./Device/Vendor/MSFT/VPNv2/PrivateNetwork",
	Format:     "bool",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "true",
	MinOSBuild: "10.0.22000",
	CSPVersion: "1.6",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "false", Description: "VPN connection is public."}, {Value: "true", Description: "VPN connection is private."}}},
}

// ProfileXML: The XML schema for provisioning all the fields of a VPN.
var ProfileXML = csp.Policy{
	Name:       "ProfileXML",
	URI:        "./Device/Vendor/MSFT/VPNv2/ProfileXML",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.14393",
	CSPVersion: "1.2",
	Allowed:    &csp.Allowed{Type: "XSD"},
}

// ProxyAutoConfigUrl: Optional. Set a URL to automatically retrieve the proxy settings.
var ProxyAutoConfigUrl = csp.Policy{
	Name:    "AutoConfigUrl",
	URI:     "./Device/Vendor/MSFT/VPNv2/Proxy/AutoConfigUrl",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "None"},
}

// ProxyManualServer: Optional. The value is the proxy server address as a fully qualified hostname or an IP address, with port appended after a colon for example, proxy.constoso.com:80.
var ProxyManualServer = csp.Policy{
	Name:    "Server",
	URI:     "./Device/Vendor/MSFT/VPNv2/Proxy/Manual/Server",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "None"},
}

// RegisterDNS: Allows registration of the connection's address in DNS.
var RegisterDNS = csp.Policy{
	Name:       "RegisterDNS",
	URI:        "./Device/Vendor/MSFT/VPNv2/RegisterDNS",
	Format:     "bool",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "false",
	MinOSBuild: "10.0.16299",
	CSPVersion: "1.3",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "false", Description: "Do not register the connection's address in DNS."}, {Value: "true", Description: "Register the connection's addresses in DNS."}}},
}

// RememberCredentials: Boolean value (true or false) for caching credentials.
var RememberCredentials = csp.Policy{
	Name:    "RememberCredentials",
	URI:     "./Device/Vendor/MSFT/VPNv2/RememberCredentials",
	Format:  "bool",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Default: "false",
	Allowed: &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "false", Description: "Do not cache credentials."}, {Value: "true", Description: "Credentials are cached whenever possible."}}},
}

// RequireVpnClientAppUI: Applicable only to AppContainer profiles.
var RequireVpnClientAppUI = csp.Policy{
	Name:       "RequireVpnClientAppUI",
	URI:        "./Device/Vendor/MSFT/VPNv2/RequireVpnClientAppUI",
	Format:     "bool",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.19628",
	CSPVersion: "1.4",
}

// RouteListAddress: Subnet address in IPv4/v6 address format which, along with the prefix will be used to determine the destination prefix to send via the VPN Interface. This is the IP address part of the destination prefix.
var RouteListAddress = csp.Policy{
	Name:    "Address",
	URI:     "./Device/Vendor/MSFT/VPNv2/RouteList/Address",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "None"},
}

// RouteListExclusionRoute: A boolean value that specifies if the route being added should point to the VPN Interface or the Physical Interface as the Gateway.
var RouteListExclusionRoute = csp.Policy{
	Name:       "ExclusionRoute",
	URI:        "./Device/Vendor/MSFT/VPNv2/RouteList/ExclusionRoute",
	Format:     "bool",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "false",
	MinOSBuild: "10.0.14393",
	CSPVersion: "1.2",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "false", Description: "This route will direct traffic over the VPN."}, {Value: "true", Description: "This route will direct traffic over the physical interface."}}},
}

// RouteListMetric: The route's metric.
var RouteListMetric = csp.Policy{
	Name:       "Metric",
	URI:        "./Device/Vendor/MSFT/VPNv2/RouteList/Metric",
	Format:     "int",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.14393",
	CSPVersion: "1.2",
	Allowed:    &csp.Allowed{Type: "None"},
}

// RouteListPrefixSize: The subnet prefix size part of the destination prefix for the route entry. This, along with the address will be used to determine the destination prefix to route through the VPN Interface.
var RouteListPrefixSize = csp.Policy{
	Name:    "PrefixSize",
	URI:     "./Device/Vendor/MSFT/VPNv2/RouteList/PrefixSize",
	Format:  "int",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "Range"},
}

// TrafficFilterListAppId: App identity for the app-based traffic filter. The value for this node can be one of the following: PackageFamilyName - This App/Id value represents the PackageFamilyName of the app. The PackageFamilyName is the unique name of a Microsoft Store application. FilePath - This App/Id value represents the full file path of the app. For example, C:\Windows\System\Notepad.exe. SYSTEM - This value enables Kernel Drivers to send traffic through VPN (for example, PING or SMB).
var TrafficFilterListAppId = csp.Policy{
	Name:    "Id",
	URI:     "./Device/Vendor/MSFT/VPNv2/TrafficFilterList/App/Id",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "None"},
}

// TrafficFilterListAppType: Returns the type of ID of the App/Id. Either PackageFamilyName, FilePath, or System.
var TrafficFilterListAppType = csp.Policy{
	Name:   "Type",
	URI:    "./Device/Vendor/MSFT/VPNv2/TrafficFilterList/App/Type",
	Format: "chr",
	Access: []string{"Get"},
}

// TrafficFilterListClaims: Specifies a rule in Security Descriptor Definition Language (SDDL) format to check against local user token.
var TrafficFilterListClaims = csp.Policy{
	Name:    "Claims",
	URI:     "./Device/Vendor/MSFT/VPNv2/TrafficFilterList/Claims",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "None"},
}

// TrafficFilterListDirection: Outbound - The traffic filter allows traffic to reach destinations matching this rule. This is the default.
var TrafficFilterListDirection = csp.Policy{
	Name:       "Direction",
	URI:        "./Device/Vendor/MSFT/VPNv2/TrafficFilterList/Direction",
	Format:     "chr",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	MinOSBuild: "10.0.19041",
	CSPVersion: "1.3",
}

// TrafficFilterListLocalAddressRanges: A list of comma separated values specifying local IP address ranges to allow.
var TrafficFilterListLocalAddressRanges = csp.Policy{
	Name:    "LocalAddressRanges",
	URI:     "./Device/Vendor/MSFT/VPNv2/TrafficFilterList/LocalAddressRanges",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "None"},
}

// TrafficFilterListLocalPortRanges: Comma Separated list of ranges for eg. 100-120,200,300-320.
var TrafficFilterListLocalPortRanges = csp.Policy{
	Name:    "LocalPortRanges",
	URI:     "./Device/Vendor/MSFT/VPNv2/TrafficFilterList/LocalPortRanges",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "RegEx"},
}

// TrafficFilterListProtocol: 0-255 number representing the ip protocol (TCP = 6, UDP = 17).
var TrafficFilterListProtocol = csp.Policy{
	Name:    "Protocol",
	URI:     "./Device/Vendor/MSFT/VPNv2/TrafficFilterList/Protocol",
	Format:  "int",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "Range"},
}

// TrafficFilterListRemoteAddressRanges: A list of comma separated values specifying remote IP address ranges to allow.
var TrafficFilterListRemoteAddressRanges = csp.Policy{
	Name:    "RemoteAddressRanges",
	URI:     "./Device/Vendor/MSFT/VPNv2/TrafficFilterList/RemoteAddressRanges",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "None"},
}

// TrafficFilterListRemotePortRanges: A list of comma separated values specifying remote port ranges to allow. For example, 100-120, 200, 300-320.
var TrafficFilterListRemotePortRanges = csp.Policy{
	Name:    "RemotePortRanges",
	URI:     "./Device/Vendor/MSFT/VPNv2/TrafficFilterList/RemotePortRanges",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "RegEx"},
}

// TrafficFilterListRoutingPolicyType: Specifies the routing policy if an App or Claims type is used in the traffic filter. The scope of this property is for this traffic filter rule alone.
var TrafficFilterListRoutingPolicyType = csp.Policy{
	Name:    "RoutingPolicyType",
	URI:     "./Device/Vendor/MSFT/VPNv2/TrafficFilterList/RoutingPolicyType",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "SplitTunnel", Description: "For this traffic filter rule, only the traffic meant for the VPN interface (as determined by the networking stack) goes over the interface. Internet traffic can continue to go over the other interfaces."}, {Value: "ForceTunnel", Description: "For this traffic rule all IP traffic must go through the VPN Interface only."}}},
}

// TrustedNetworkDetection: Comma separated string to identify the trusted network. VPN will not connect automatically when the user is on their corporate wireless network where protected resources are directly accessible to the device.
var TrustedNetworkDetection = csp.Policy{
	Name:    "TrustedNetworkDetection",
	URI:     "./Device/Vendor/MSFT/VPNv2/TrustedNetworkDetection",
	Format:  "chr",
	Access:  []string{"Add", "Delete", "Get", "Replace"},
	Allowed: &csp.Allowed{Type: "None"},
}

// UseRasCredentials: Determines whether the credential manager will save ras credentials after a connection.
var UseRasCredentials = csp.Policy{
	Name:       "UseRasCredentials",
	URI:        "./Device/Vendor/MSFT/VPNv2/UseRasCredentials",
	Format:     "bool",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "true",
	MinOSBuild: "10.0.22000",
	CSPVersion: "1.6",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "false", Description: "Ras Credentials are not saved."}, {Value: "true", Description: "Ras Credentials are saved."}}},
}

// DeviceTunnel: If turned on a device tunnel profile does four things.
var DeviceTunnel = csp.Policy{
	Name:       "DeviceTunnel",
	URI:        "./Device/Vendor/MSFT/VPNv2/DeviceTunnel",
	Format:     "bool",
	Access:     []string{"Add", "Delete", "Get", "Replace"},
	Default:    "false",
	MinOSBuild: "10.0.16299",
	CSPVersion: "1.3",
	Allowed:    &csp.Allowed{Type: "ENUM", Enum: []csp.EnumValue{{Value: "false", Description: "This is not a device tunnel profile."}, {Value: "true", Description: "This is a device tunnel profile."}}},
}

// All lists every policy in this CSP area.
var All = []csp.Policy{
	APNBindingAccessPointName,
	APNBindingAuthenticationType,
	APNBindingIsCompressionEnabled,
	APNBindingPassword,
	APNBindingProviderId,
	APNBindingUserName,
	AlwaysOn,
	AlwaysOnActive,
	AppTriggerListAppId,
	AppTriggerListAppType,
	ByPassForLocal,
	DataEncryption,
	DeviceComplianceEnabled,
	DeviceComplianceSsoEku,
	DeviceComplianceSsoEnabled,
	DeviceComplianceSsoIssuerHash,
	DisableAdvancedOptionsEditButton,
	DisableDisconnectButton,
	DisableIKEv2Fragmentation,
	DnsSuffix,
	DomainNameInformationListAutoTrigger,
	DomainNameInformationListDnsServers,
	DomainNameInformationListDomainName,
	DomainNameInformationListDomainNameType,
	DomainNameInformationListPersistent,
	DomainNameInformationListWebProxyServers,
	EdpModeId,
	IPv4InterfaceMetric,
	IPv6InterfaceMetric,
	NativeProfileAuthenticationCertificateEku,
	NativeProfileAuthenticationCertificateIssuer,
	NativeProfileAuthenticationEapConfiguration,
	NativeProfileAuthenticationEapType,
	NativeProfileAuthenticationMachineMethod,
	NativeProfileAuthenticationUserMethod,
	NativeProfileCryptographySuiteAuthenticationTransformConstants,
	NativeProfileCryptographySuiteCipherTransformConstants,
	NativeProfileCryptographySuiteDHGroup,
	NativeProfileCryptographySuiteEncryptionMethod,
	NativeProfileCryptographySuiteIntegrityCheckMethod,
	NativeProfileCryptographySuitePfsGroup,
	NativeProfileDisableClassBasedDefaultRoute,
	NativeProfileL2tpPsk,
	NativeProfileNativeProtocolType,
	NativeProfilePlumbIKEv2TSAsRoutes,
	NativeProfileProtocolListNativeProtocolListType,
	NativeProfileProtocolListRetryTimeInHours,
	NativeProfileRoutingPolicyType,
	NativeProfileServers,
	NetworkOutageTime,
	PluginProfileCustomConfiguration,
	PluginProfilePluginPackageFamilyName,
	PluginProfileServerUrlList,
	PrivateNetwork,
	ProfileXML,
	ProxyAutoConfigUrl,
	ProxyManualServer,
	RegisterDNS,
	RememberCredentials,
	RequireVpnClientAppUI,
	RouteListAddress,
	RouteListExclusionRoute,
	RouteListMetric,
	RouteListPrefixSize,
	TrafficFilterListAppId,
	TrafficFilterListAppType,
	TrafficFilterListClaims,
	TrafficFilterListDirection,
	TrafficFilterListLocalAddressRanges,
	TrafficFilterListLocalPortRanges,
	TrafficFilterListProtocol,
	TrafficFilterListRemoteAddressRanges,
	TrafficFilterListRemotePortRanges,
	TrafficFilterListRoutingPolicyType,
	TrustedNetworkDetection,
	UseRasCredentials,
	DeviceTunnel,
}
